"""Loop-interaction map (#10823) — pure computation + report rendering.

The pathology no per-loop instrument can see: ~70 loops on one codebase, where
one loop's fix is another loop's disturbance. Every existing series is per-loop;
this is a property of the loop *population*. Read from merge history (Pattern B —
sense and record, never fix).

Two signals, both derived from per-merge churn (``git log --numstat``):

1. **Contested surfaces** — the fix-as-disturbance signature. A file where content
   is repeatedly *added and removed* (high ``reversal_churn = min(added, deleted)``
   summed over the window) is being fought over, not grown. This is the sharpest
   population-level signal: a surface two subsystems keep undoing each other on.
2. **Logical coupling** — files that change together across merges (temporal
   co-change). Frequently co-changed files are coupled subsystems; the god-files
   surface as coupling hubs (consistent with ``erosion.concentration``).

Loop attribution is deliberately NOT attempted: the fingerprint (#10820) showed
that generic ``hydraflow-find`` work is not attributable to a single loop, so a
"loop-by-loop" matrix would be fabricated. This maps the *surfaces and their
churn* — the honest, derivable truth — and is meant to be read alongside the
#10820 fingerprint's rework hot-paths and the concentration god-files.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from itertools import combinations

from stillness.fingerprint import is_generated_artifact


@dataclass(frozen=True)
class FileChurn:
    path: str
    added: int
    deleted: int


@dataclass(frozen=True)
class MergeChurn:
    sha: str
    merged_at: datetime
    files: tuple[FileChurn, ...]


@dataclass(frozen=True)
class ContestedSurface:
    path: str
    merges: int  # distinct merges touching it in-window
    added: int
    deleted: int

    @property
    def reversal_churn(self) -> int:
        """Lines both added and (over the window) removed — the contested volume."""
        return min(self.added, self.deleted)


@dataclass(frozen=True)
class Coupling:
    file_a: str
    file_b: str
    co_changes: int


# Lock files + generated docs are MECHANICAL churn — regenerated by a dependency
# bump or an audit run, not two subsystems undoing each other. The first live run
# had src/ui/package-lock.json (564) and a prompt-audit doc topping the contested
# list; excluding them keeps the signal to genuine SOURCE contention.
_LOCK_NAMES = {"package-lock.json", "uv.lock", "poetry.lock", "yarn.lock"}


def _is_mechanical_churn(path: str) -> bool:
    base = path.rsplit("/", 1)[-1]
    return (
        is_generated_artifact(path)
        or base in _LOCK_NAMES
        or base.startswith("prompt-audit-")
    )


def _relevant(files: tuple[FileChurn, ...]) -> list[FileChurn]:
    return [f for f in files if not _is_mechanical_churn(f.path)]


def _in_window(
    merges: list[MergeChurn], *, now: datetime, weeks: int
) -> list[MergeChurn]:
    start = now - timedelta(weeks=weeks)
    return [m for m in merges if start <= m.merged_at <= now]


def contested_surfaces(
    merges: list[MergeChurn], *, now: datetime, weeks: int, top: int = 15
) -> list[ContestedSurface]:
    added: Counter[str] = Counter()
    deleted: Counter[str] = Counter()
    touch: Counter[str] = Counter()
    for m in _in_window(merges, now=now, weeks=weeks):
        for f in _relevant(m.files):
            added[f.path] += f.added
            deleted[f.path] += f.deleted
            touch[f.path] += 1
    surfaces = [
        ContestedSurface(path=p, merges=touch[p], added=added[p], deleted=deleted[p])
        for p in touch
    ]
    surfaces.sort(key=lambda s: (-s.reversal_churn, -s.merges, s.path))
    return surfaces[:top]


def logical_coupling(
    merges: list[MergeChurn],
    *,
    now: datetime,
    weeks: int,
    min_merges: int = 5,
    top: int = 15,
) -> list[Coupling]:
    """Rank file pairs that change together, among files touched >= min_merges."""
    window = _in_window(merges, now=now, weeks=weeks)
    touch: Counter[str] = Counter()
    for m in window:
        for f in _relevant(m.files):
            touch[f.path] += 1
    frequent = {p for p, n in touch.items() if n >= min_merges}
    pairs: Counter[tuple[str, str]] = Counter()
    for m in window:
        files = sorted({f.path for f in _relevant(m.files) if f.path in frequent})
        for a, b in combinations(files, 2):
            pairs[(a, b)] += 1
    ranked = [
        Coupling(file_a=a, file_b=b, co_changes=n)
        for (a, b), n in pairs.most_common(top)
    ]
    return ranked


@dataclass
class InteractionMap:
    generated_at: datetime
    weeks: int
    total_merges: int
    contested: list[ContestedSurface]
    couplings: list[Coupling]
    cross_refs: list[str] = field(default_factory=list)


def build_interaction_map(
    merges: list[MergeChurn], *, now: datetime, weeks: int
) -> InteractionMap:
    window = _in_window(merges, now=now, weeks=weeks)
    return InteractionMap(
        generated_at=now,
        weeks=weeks,
        total_merges=len(window),
        contested=contested_surfaces(merges, now=now, weeks=weeks),
        couplings=logical_coupling(merges, now=now, weeks=weeks),
    )


def render_report(im: InteractionMap) -> str:
    lines: list[str] = []
    a = lines.append
    a("# Loop-Interaction Map (#10823)")
    a("")
    a(
        f"Read-only diagnostic — generated {im.generated_at:%Y-%m-%d} over the "
        f"trailing **{im.weeks} weeks** ({im.total_merges} merges). Surfaces the "
        "population-level pathology no per-loop series shows: where one loop's fix "
        "is another's disturbance. Loop attribution is not attempted (not "
        "derivable — see #10820); this maps the contested *surfaces*. Read "
        "alongside the #10820 fingerprint and the concentration god-files."
    )
    a("")
    a("## Contested surfaces (fix-as-disturbance)")
    a("")
    a(
        "Files where content is repeatedly **added and removed** — a surface two "
        "subsystems keep undoing. Ranked by reversal churn = min(total added, "
        "total deleted); regen artifacts excluded."
    )
    a("")
    if im.contested:
        a("| # | Path | Reversal churn | +added | −deleted | Merges |")
        a("|---|---|---|---|---|---|")
        for i, s in enumerate(im.contested, 1):
            a(
                f"| {i} | `{s.path}` | **{s.reversal_churn}** | {s.added} "
                f"| {s.deleted} | {s.merges} |"
            )
    else:
        a("_No merges in window._")
    a("")
    a("## Logical coupling (files that change together)")
    a("")
    a(
        "File pairs co-modified across merges (temporal coupling). God-files "
        "surface as hubs — consistent with `erosion.concentration`."
    )
    a("")
    if im.couplings:
        a("| # | File A | File B | Co-changes |")
        a("|---|---|---|---|")
        for i, c in enumerate(im.couplings, 1):
            a(f"| {i} | `{c.file_a}` | `{c.file_b}` | {c.co_changes} |")
    else:
        a("_No frequently co-changed files in window._")
    a("")
    if im.cross_refs:
        a("## Cross-reference")
        for line in im.cross_refs:
            a(f"- {line}")
        a("")
    return "\n".join(lines)
