"""Deterministic render of the second-order vitals verdict (#10373).

Two surfaces, one source: the generated ``docs/arch/generated/second-order-vitals.md``
report and the ``/api/diagnostics/second-order-vitals`` dashboard payload both
derive from the same :class:`~vitals.models.VitalsVerdict`, so the verdict is
always explainable from its inputs on the same page — every family's series,
its control limit, and its residual are shown, whatever the verdict. Pure
functions: same verdict in → same bytes out.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from vitals.models import VitalsVerdict

_VERDICT_GLYPH = {
    "green": "🟢 green",
    "watch": "🟡 watch",
    "diverging": "🔴 diverging",
}


def render_second_order_vitals_markdown(
    verdict: VitalsVerdict, *, now: datetime, window_days: int
) -> str:
    """Render the vitals report as deterministic Markdown.

    The verdict headline, the primary-health precondition, the k-of-5 family
    tally, and a per-series control-limit table (value / centre / UCL /
    residual) are all shown so a reader can reconstruct the verdict by hand —
    the "explainable from its inputs on the same page" requirement.
    """
    lines: list[str] = []
    lines.append("# Second-order vitals")
    lines.append("")
    lines.append(
        "> Generated by `SecondOrderVitalsLoop` (#10373) — the residual monitor "
        "over the falsification-instrument set: it watches whether several "
        "independent second-order signals drift adverse together WHILE the "
        "primary gates stay green (green-while-dying). Read-only (ADR-0029 "
        "Pattern B): it computes and reports, never remediates or gates."
    )
    lines.append("")
    lines.append(
        f"**Verdict:** {_VERDICT_GLYPH.get(verdict.verdict, verdict.verdict)} "
        f"({verdict.coverage_label})"
    )
    lines.append("")
    lines.append(
        f"- primary health: {'green' if verdict.primary_health_green else 'not green'} "
        "(watch/diverging can only be reached while primary health is green)"
    )
    lines.append(
        f"- families above their control limits (sustained): "
        f"**{verdict.k} of {verdict.total_families}** "
        f"({', '.join(verdict.breaching_families) if verdict.breaching_families else 'none'})"
    )
    lines.append(f"- window: {window_days}d · as of {now.isoformat()}")
    lines.append("")
    lines.append("## Families")
    lines.append("")
    lines.append("| family | reporting | above control limit (sustained) |")
    lines.append("|---|---|---|")
    for fam in verdict.families:
        lines.append(
            f"| {fam.family} | {'yes' if fam.reporting else 'no (too young)'} "
            f"| {'YES' if fam.breaching else 'no'} |"
        )
    lines.append("")
    lines.append("## Contributing series (each vs its own Shewhart limit)")
    lines.append("")
    lines.append("| series | latest | centre | UCL | residual | windows | breaching |")
    lines.append("|---|---|---|---|---|---|---|")
    for fam in verdict.families:
        for s in fam.series:
            lines.append(
                f"| {s.label} | {s.value:g} | {s.center:g} | {s.ucl:g} "
                f"| {s.residual:+g} | {s.windows} | {'YES' if s.breaching else 'no'} |"
            )
    lines.append("")
    lines.append(
        "> Residual = latest − UCL (positive means above the control limit). A "
        "family counts toward the k-of-5 divergence tally only when one of its "
        "series stays above its limit for the sustained-window count — "
        "single-window spikes and single-series noise belong to that "
        "instrument's own finding path, not here."
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def verdict_record(verdict: VitalsVerdict, *, ts: str) -> dict[str, Any]:
    """The append-only ``vitals.jsonl`` row for one evaluation.

    A compact, machine-readable snapshot so "how long were we in watch" is
    answerable from the history alone.
    """
    return {
        "ts": ts,
        "verdict": verdict.verdict,
        "k": verdict.k,
        "breaching_families": list(verdict.breaching_families),
        "reporting_families": verdict.reporting_families,
        "total_families": verdict.total_families,
        "primary_health_green": verdict.primary_health_green,
    }


def verdict_payload(verdict: VitalsVerdict) -> dict[str, Any]:
    """Full dashboard/endpoint payload — the verdict plus its explanation.

    Mirrors the report: the same family/series breakdown, JSON-serialisable, so
    the dashboard panel is as legible as the generated page.
    """
    return {
        "verdict": verdict.verdict,
        "k": verdict.k,
        "breaching_families": list(verdict.breaching_families),
        "reporting_families": verdict.reporting_families,
        "total_families": verdict.total_families,
        "coverage_label": verdict.coverage_label,
        "primary_health_green": verdict.primary_health_green,
        "families": [
            {
                "family": fam.family,
                "reporting": fam.reporting,
                "breaching": fam.breaching,
                "series": [
                    {
                        "name": s.name,
                        "label": s.label,
                        "value": s.value,
                        "center": s.center,
                        "ucl": s.ucl,
                        "residual": s.residual,
                        "windows": s.windows,
                        "reporting": s.reporting,
                        "breaching": s.breaching,
                    }
                    for s in fam.series
                ],
            }
            for fam in verdict.families
        ],
    }


def latest_verdict_payload(records: list[dict[str, Any]]) -> dict[str, Any]:
    """The most recent persisted ``vitals.jsonl`` record, or a green default.

    The endpoint's data source. With no history yet it returns a green,
    zero-coverage verdict rather than erroring — an unbuilt monitor is honestly
    "green (0-of-5 reporting)", never an alarm.
    """
    if records:
        return records[-1]
    return {
        "ts": "",
        "verdict": "green",
        "k": 0,
        "breaching_families": [],
        "reporting_families": 0,
        "total_families": 5,
        "primary_health_green": True,
    }
