"""Erosion trend rollup (#10367, v2 of epic #10104): month-over-month surfaces.

Epic #10104 shipped per-change erosion sensing (``erosion.spread`` #10105,
``erosion.scatter`` #10106) but surfaced no trend — the Ch 16 retrospective
("is entanglement growing month over month?") was a one-off script, not an
instrument. This module makes it standing:

* ``ChangeDatapoint`` — one merged change's erosion reading (files touched,
  modules crossed, scatter findings, duplication density), tagged with its
  detection month. Persisted append-only via ``TrendStore``.
* ``compute_monthly_trends`` — the pure rollup: percent of changes crossing
  ≥3 modules, mean files-touched, mean duplication density, summed scatter
  findings, per month. Pure over synthetic datapoints, unit-testable.
* ``render_erosion_trends_markdown`` — the generated
  ``docs/arch/generated/erosion-trends.md`` surface (gitignored, rewritten by
  the loop each tick, like ``loop-fitness.md``).
"""

from __future__ import annotations

import json
import logging
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger("hydraflow.erosion_trends")

#: A change is "cross-cutting" once it spans this many distinct modules — the
#: same K threshold ``erosion.scatter`` uses for its scatter signal.
_CROSS_MODULE_THRESHOLD = 3


@dataclass(frozen=True)
class ChangeDatapoint:
    """One merged change's erosion reading, tagged with its detection month."""

    month: str  # "YYYY-MM"
    files_touched: int
    modules_crossed: int
    scatter_findings: int
    duplication_density: float

    def to_json_dict(self) -> dict[str, Any]:
        return {
            "month": self.month,
            "files_touched": self.files_touched,
            "modules_crossed": self.modules_crossed,
            "scatter_findings": self.scatter_findings,
            "duplication_density": self.duplication_density,
        }

    @classmethod
    def from_json_dict(cls, raw: dict[str, Any]) -> ChangeDatapoint:
        return cls(
            month=str(raw.get("month", "")),
            files_touched=int(raw.get("files_touched", 0)),
            modules_crossed=int(raw.get("modules_crossed", 0)),
            scatter_findings=int(raw.get("scatter_findings", 0)),
            duplication_density=float(raw.get("duplication_density", 0.0)),
        )


@dataclass(frozen=True)
class MonthlyTrendRow:
    """Aggregated erosion metrics for one month — the four trend surfaces."""

    month: str
    change_count: int
    pct_crossing_3_modules: float
    mean_files_touched: float
    duplication_density: float
    scatter_findings: int


def compute_monthly_trends(datapoints: list[ChangeDatapoint]) -> list[MonthlyTrendRow]:
    """Pure: bucket per-change datapoints into month-over-month trend rows.

    Rows are sorted ascending by month. All four trend metrics are computed:
    percent of changes crossing ≥3 modules, mean files-touched per change,
    mean duplication density, and summed scatter finding counts.
    """
    buckets: dict[str, list[ChangeDatapoint]] = defaultdict(list)
    for dp in datapoints:
        if dp.month:
            buckets[dp.month].append(dp)

    rows: list[MonthlyTrendRow] = []
    for month in sorted(buckets):
        items = buckets[month]
        n = len(items)
        crossing = sum(
            1 for dp in items if dp.modules_crossed >= _CROSS_MODULE_THRESHOLD
        )
        rows.append(
            MonthlyTrendRow(
                month=month,
                change_count=n,
                pct_crossing_3_modules=(100.0 * crossing / n) if n else 0.0,
                mean_files_touched=(
                    sum(dp.files_touched for dp in items) / n if n else 0.0
                ),
                duplication_density=(
                    sum(dp.duplication_density for dp in items) / n if n else 0.0
                ),
                scatter_findings=sum(dp.scatter_findings for dp in items),
            )
        )
    return rows


def render_erosion_trends_markdown(rows: list[MonthlyTrendRow]) -> str:
    """Render the month-over-month erosion trend report as Markdown."""
    lines: list[str] = []
    lines.append("# Erosion trends")
    lines.append("")
    lines.append(
        "> Generated by `EscapeLedgerLoop` (#10367, v2 of epic #10104) — the "
        "standing month-over-month view of codebase entanglement. Read-only "
        "(ADR-0029 Pattern B): senses and records, never gates."
    )
    lines.append("")
    lines.append(
        "| month | changes | % crossing ≥3 modules | mean files/change "
        "| duplication /KLOC | scatter findings |"
    )
    lines.append("|---|---|---|---|---|---|")
    for row in rows:
        lines.append(
            f"| {row.month} | {row.change_count} | "
            f"{row.pct_crossing_3_modules:.1f}% | "
            f"{row.mean_files_touched:.2f} | "
            f"{row.duplication_density:.2f} | {row.scatter_findings} |"
        )
    if not rows:
        lines.append("| (no changes recorded yet) | 0 | 0.0% | 0.00 | 0.00 | 0 |")
    lines.append("")
    return "\n".join(lines) + "\n"


class TrendStore:
    """Append-only JSONL store for erosion trend datapoints (one per change)."""

    def __init__(self, path: Path) -> None:
        self._path = path

    @property
    def path(self) -> Path:
        return self._path

    def read_all(self) -> list[ChangeDatapoint]:
        if not self._path.exists():
            return []
        rows: list[ChangeDatapoint] = []
        for raw_line in self._path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line:
                continue
            try:
                raw = json.loads(line)
            except json.JSONDecodeError:
                logger.warning("TrendStore: skipping malformed datapoint line")
                continue
            if isinstance(raw, dict):
                rows.append(ChangeDatapoint.from_json_dict(raw))
        return rows

    def append(self, datapoint: ChangeDatapoint) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        with self._path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(datapoint.to_json_dict(), sort_keys=False) + "\n")
