"""Build-outcome screening for ``ImplementPhase``.

Extracted VERBATIM from ``src/implement_phase.py`` (god-class
decomposition, Refs #11547) as a mixin — the shape ``review_phase/`` already
uses. ``ImplementPhase`` inherits it, so every method here still resolves as
an attribute of ``ImplementPhase`` and instance/class-level patching in tests
still lands.

One concern: classifying what a finished build actually delivered, and the two
failure shapes that never push — zero commits and null delivery (a diff of
planner diagrams / generated artifacts only, #9480). Each writes its own issue
comment and marks the attempt failed so the attempt cap retries with corrective
context.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING

from implement_spec_reviewer import compute_branch_changed_files

if TYPE_CHECKING:
    from agent import AgentRunner
    from config import HydraFlowConfig
    from models import Task, WorkerResult
    from state import StateTracker
    from task_source import TaskTransitioner

logger = logging.getLogger("hydraflow.implement_phase")


class ImplementScreeningMixin:
    """Build-outcome screening for ``ImplementPhase``."""

    # ------------------------------------------------------------------
    # Collaborator seams — provided by ``ImplementPhase.__init__`` or by
    # a sibling mixin. The method declarations are TYPE_CHECKING-only
    # on purpose: a runtime ``...`` body would win over the
    # real implementation whenever this mixin precedes the
    # implementing one in ``ImplementPhase``'s MRO.
    # ------------------------------------------------------------------
    _agents: AgentRunner
    _config: HydraFlowConfig
    _state: StateTracker
    _transitioner: TaskTransitioner

    @staticmethod
    def _is_zero_commit_failure(result: WorkerResult) -> bool:
        """Check whether *result* represents a zero-commit implementation failure.

        Any failed run with no commits is a zero-commit failure — not just
        the canonical "No commits found on branch" error. ProcessLookupError
        (subprocess killed mid-run), AuthenticationRetryError (credentials
        expired), and any other early-exit Exception path that leaves
        commits=0 must route to _handle_zero_commits, not push/PR.
        """
        return not result.success and result.commits == 0

    async def _is_null_delivery(self, result: WorkerResult) -> bool:
        """Return ``True`` if the branch diff is diagrams/auto-generated only.

        Computes the changed-file list for the branch and classifies it with
        ``null_delivery.is_null_delivery``. Fails open (returns ``False``) when
        the diff cannot be computed, so a transient git error never blocks a
        real implementation.
        """
        from null_delivery import is_null_delivery  # noqa: PLC0415

        changed = await self._branch_changed_files(result)
        return is_null_delivery(changed)

    async def _branch_changed_files(self, result: WorkerResult) -> list[str]:
        """Return the changed file paths of the result's branch vs base, or []."""
        if not result.workspace_path or not Path(result.workspace_path).is_dir():
            return []
        runner = getattr(self._agents, "_runner", None)
        run_simple = getattr(runner, "run_simple", None) if runner else None
        if run_simple is None:
            return []
        return await compute_branch_changed_files(
            Path(result.workspace_path),
            result.branch,
            self._config.base_branch(),
            runner_run_simple=run_simple,
            timeout=self._config.git_command_timeout,
        )

    async def _handle_null_delivery(
        self, issue: Task, result: WorkerResult
    ) -> WorkerResult:
        """Handle a null-delivery failure: no PR, mark failed, allow retry.

        Mirrors ``_handle_zero_commits`` — the attempt-cap mechanism retries
        with corrective ``prior_failure`` context rather than escalating
        immediately.
        """
        attempts = self._state.get_issue_attempts(issue.id)
        logger.warning(
            "Issue #%d: null delivery (diagrams/auto-generated only) "
            "after implementation (attempt %d/%d)",
            issue.id,
            attempts,
            self._config.max_issue_attempts,
        )
        await self._transitioner.post_comment(
            issue.id,
            "## Implementation Failed — Null Delivery\n\n"
            "The implementation produced only planner diagrams / "
            "auto-generated artifacts and no code, tests, or assets. "
            "No PR was opened (merging one would have falsely closed this "
            f"issue). Attempt {attempts}/{self._config.max_issue_attempts}.\n\n"
            "---\n"
            "*Generated by HydraFlow Implementer*",
        )
        self._state.mark_issue(issue.id, "failed")
        return result

    async def _handle_zero_commits(
        self, issue: Task, result: WorkerResult
    ) -> WorkerResult:
        """Handle a zero-commit failure on the retry path.

        Reached only when ``zero-commit-abort`` fell through — the abort is
        disabled (``implement_no_progress_abort_attempts == 0``) or this
        attempt is below its threshold (#11568). Marks as failed so the
        attempt-cap mechanism can retry with corrective context
        (prior_failure feedback) instead of escalating immediately.
        """
        attempts = self._state.get_issue_attempts(issue.id)
        logger.warning(
            "Issue #%d: zero commits after implementation (attempt %d/%d)",
            issue.id,
            attempts,
            self._config.max_issue_attempts,
        )
        await self._transitioner.post_comment(
            issue.id,
            "## Implementation Failed — Zero Commits\n\n"
            "The implementation agent ran but produced no commits. "
            f"Attempt {attempts}/{self._config.max_issue_attempts}.\n\n"
            "---\n"
            "*Generated by HydraFlow Implementer*",
        )
        self._state.mark_issue(issue.id, "failed")
        return result

    def _transcript_tail(self, result: WorkerResult) -> str | None:
        """Last ``error_output_max_chars`` of the run transcript, or ``None``."""
        transcript = result.transcript or ""
        if not transcript:
            return None
        return transcript[-self._config.error_output_max_chars :]
