"""Tests for ``decomposition_docs`` -- bounded doc-context retrieval for
decompose-to-converge (ADR-0105, Task 4).

Hermetic: every test seeds a tiny ``adr_xref.md`` + ADR markdown files +
wiki topic pages under ``tmp_path`` and points ``repo_root`` at that
directory. None of these tests depend on this repo's own real generated
files (``docs/arch/generated/adr_xref.md``, ``docs/wiki/*.md``), which
drift independently of this module and would make the tests flaky.

Covers:
* Touched files mapping to known ADRs via the "## Module -> ADRs" table
  return those ADRs' title + Decision excerpt, ranked by touched-file
  hit count and bounded to ``max_adrs``.
* An ADR cited by the table but missing its own markdown file is
  skipped gracefully (not an error).
* Touched files with no module mapping (unmapped module, non-``src/``
  path, non-Python file) return a graceful empty result.
* Wiki topic-page entries matching touched-file keywords are returned,
  ranked by match strength and bounded to ``max_wiki``.
* A missing/nonexistent repo_root never raises.
"""

from __future__ import annotations

from pathlib import Path

from decomposition_docs import gather_decomposition_docs

# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------


def _write_xref(repo_root: Path, module_rows: list[tuple[str, list[str]]]) -> None:
    xref_dir = repo_root / "docs" / "arch" / "generated"
    xref_dir.mkdir(parents=True, exist_ok=True)
    rows = "\n".join(
        f"| `{module}` | {', '.join(adrs)} |" for module, adrs in module_rows
    )
    text = (
        "# ADR Cross-Reference\n\n"
        "<!-- generated by arch.generators.adr_cross_reference; do not hand-edit -->\n\n"
        "## ADR → Modules\n\n| ADR | Modules cited |\n|---|---|\n"
        "| ADR-0001 | `src.config` |\n\n"
        "## Module → ADRs\n\n| Module | Cited by |\n|---|---|\n"
        f"{rows}\n\n<!-- arch:generated -->\n"
    )
    (xref_dir / "adr_xref.md").write_text(text)


def _write_adr(repo_root: Path, number: int, title: str, decision: str) -> None:
    adr_dir = repo_root / "docs" / "adr"
    adr_dir.mkdir(parents=True, exist_ok=True)
    text = (
        f"# ADR-{number:04d}: {title}\n\n"
        "**Status:** Accepted\n\n"
        "## Context\n\nSome context goes here.\n\n"
        f"## Decision\n\n{decision}\n\n"
        "## Consequences\n\nSome consequences go here.\n"
    )
    slug = title.lower().replace(" ", "-")
    (adr_dir / f"{number:04d}-{slug}.md").write_text(text)


def _write_wiki_topic(
    repo_root: Path, name: str, entries: list[tuple[str, str]]
) -> None:
    wiki_dir = repo_root / "docs" / "wiki"
    wiki_dir.mkdir(parents=True, exist_ok=True)
    chunks = [f"# {name.title()}\n"]
    for title, prose in entries:
        chunks.append(
            f"\n## {title}\n\n{prose}\n\n```json:entry\n"
            '{"id": "01TESTFAKE0000000000000000"}\n```\n'
        )
    (wiki_dir / f"{name}.md").write_text("".join(chunks))


# ---------------------------------------------------------------------------
# ADR section
# ---------------------------------------------------------------------------


class TestAdrSection:
    """Touched files -> module -> "## Module -> ADRs" table -> excerpts."""

    def test_touched_files_resolve_to_ranked_adrs_bounded_to_max_adrs(
        self, tmp_path: Path
    ) -> None:
        _write_xref(
            tmp_path,
            [
                ("src.config", ["ADR-0001", "ADR-0002"]),
                ("src.pr_manager", ["ADR-0001", "ADR-0003"]),
            ],
        )
        _write_adr(tmp_path, 1, "Five Loops", "Run five concurrent asyncio loops.")
        _write_adr(tmp_path, 2, "Labels State Machine", "Use GitHub labels as state.")
        _write_adr(tmp_path, 3, "Worktrees", "Use git worktrees for isolation.")

        result = gather_decomposition_docs(
            ["src/config.py", "src/pr_manager.py"],
            repo_root=tmp_path,
            max_adrs=2,
            max_wiki=5,
        )

        # ADR-0001 is cited by both touched files (count=2) -> ranked first.
        assert "ADR-0001" in result
        assert "Run five concurrent asyncio loops." in result
        # ADR-0002 and ADR-0003 tie at count=1; lower id wins the tie-break.
        assert "ADR-0002" in result
        # Bounded to max_adrs=2 -- the tied loser is excluded.
        assert "ADR-0003" not in result
        assert result.count("### ADR-") == 2

    def test_adr_cited_by_table_but_missing_markdown_file_is_skipped(
        self, tmp_path: Path
    ) -> None:
        _write_xref(tmp_path, [("src.config", ["ADR-0099"])])
        # Deliberately do not write docs/adr/0099-*.md.

        result = gather_decomposition_docs(
            ["src/config.py"], repo_root=tmp_path, max_adrs=3, max_wiki=5
        )

        assert result == ""

    def test_unknown_touched_files_return_graceful_empty(self, tmp_path: Path) -> None:
        _write_xref(tmp_path, [("src.config", ["ADR-0001"])])
        _write_adr(tmp_path, 1, "Five Loops", "Run five concurrent asyncio loops.")

        result = gather_decomposition_docs(
            [
                "src/totally_unmapped_module.py",
                "README.md",
                "tests/test_something.py",
            ],
            repo_root=tmp_path,
            max_adrs=3,
            max_wiki=5,
        )

        assert result == ""


# ---------------------------------------------------------------------------
# Wiki section
# ---------------------------------------------------------------------------


class TestWikiSection:
    """Touched files -> keywords -> wiki topic-page entry match -> excerpts."""

    def test_matched_entries_are_bounded_to_max_wiki_in_document_order(
        self, tmp_path: Path
    ) -> None:
        _write_wiki_topic(
            tmp_path,
            "gotchas",
            entries=[
                ("Config validators are the source of truth", "Config objects rule."),
                ("Unrelated entry about pricing", "Pricing refresh notes."),
                ("Config schema evolution notes", "More about config schemas."),
                ("Config caching gotcha", "Caching config values safely."),
            ],
        )

        result = gather_decomposition_docs(
            ["src/config.py"], repo_root=tmp_path, max_adrs=3, max_wiki=2
        )

        assert "Config validators are the source of truth" in result
        assert "Config schema evolution notes" in result
        # Third matching entry is excluded by the max_wiki=2 bound.
        assert "Config caching gotcha" not in result
        # Non-matching entry never scored in the first place.
        assert "Unrelated entry about pricing" not in result
        assert result.count("### ") == 2

    def test_entries_matching_more_keywords_rank_above_earlier_weaker_matches(
        self, tmp_path: Path
    ) -> None:
        _write_wiki_topic(
            tmp_path,
            "patterns",
            entries=[
                ("Config only mention", "Talks about config alone."),
                (
                    "Config and manager both mentioned here",
                    "Talks about config and the pr manager together.",
                ),
            ],
        )

        result = gather_decomposition_docs(
            ["src/config.py", "src/pr_manager.py"],
            repo_root=tmp_path,
            max_adrs=3,
            max_wiki=1,
        )

        # Two-keyword match outranks the earlier one-keyword match even
        # though it appears later in the source document.
        assert "Config and manager both mentioned here" in result
        assert "Config only mention" not in result

    def test_index_page_is_never_scanned_for_entries(self, tmp_path: Path) -> None:
        wiki_dir = tmp_path / "docs" / "wiki"
        wiki_dir.mkdir(parents=True)
        (wiki_dir / "index.md").write_text(
            "# Wiki Index\n\n## Config wiki index heading\n\nShould never surface.\n"
        )

        result = gather_decomposition_docs(
            ["src/config.py"], repo_root=tmp_path, max_adrs=3, max_wiki=5
        )

        assert result == ""


# ---------------------------------------------------------------------------
# Graceful / never-raises behavior
# ---------------------------------------------------------------------------


class TestGracefulFailure:
    def test_empty_touched_files_returns_empty_string(self, tmp_path: Path) -> None:
        assert gather_decomposition_docs([], repo_root=tmp_path) == ""

    def test_nonexistent_repo_root_returns_empty_without_raising(self) -> None:
        result = gather_decomposition_docs(
            ["src/config.py"], repo_root=Path("/nonexistent/hydraflow-test-root")
        )

        assert result == ""

    def test_repo_root_with_no_generated_docs_at_all_returns_empty(
        self, tmp_path: Path
    ) -> None:
        result = gather_decomposition_docs(["src/config.py"], repo_root=tmp_path)

        assert result == ""
