from adr_index import ADR, Check
from arch.generators.adr_conformance import render_adr_conformance


def test_render_has_static_map_reverse_index_and_manual_section():
    adrs = [
        ADR(
            number=49,
            title="Kill switch",
            status="Accepted",
            summary="",
            enforcement="enforced",
            enforced_by=(
                Check("pytest", "tests/t.py::test_x", "pytest:tests/t.py::test_x"),
            ),
        ),
        ADR(
            number=42,
            title="Two-tier branch",
            status="Accepted",
            summary="",
            enforcement="manual",
            enforced_by=(Check("prose", "ruleset review", "ruleset review"),),
        ),
        ADR(
            number=3,
            title="Worktrees",
            status="Accepted",
            summary="",
            enforcement="decision-of-record",
        ),
    ]
    md = render_adr_conformance(adrs)
    assert "ADR-0049" in md and "enforced" in md
    assert "pytest:tests/t.py::test_x" in md  # cited check shown
    assert "## Manual ADRs" in md and "ruleset review" in md
    # reverse index: the check maps back to the ADR it protects
    assert "test_x" in md
    assert "generated by" in md  # do-not-hand-edit preamble
