"""Render the intervention tally to Markdown (#10369).

Follows ``escape-ledger.md``'s generated-report convention: a runtime-written
``docs/arch/generated/intervention-tally.md`` (gitignored — the loop rewrites
it each tick), NOT an ``arch-regen`` artifact. Pure over
``list[InterventionRecord]`` + injected merge count / active-loop count /
``now`` so the rendered numbers match the metrics module exactly and the
render is unit-testable.
"""

from __future__ import annotations

from datetime import datetime

from intervention import metrics
from intervention.models import ALL_CLASSES, InterventionRecord


def render_intervention_tally_markdown(
    records: list[InterventionRecord],
    *,
    now: datetime,
    merge_count_30d: int,
    active_loop_count: int,
) -> str:
    """Render the full intervention-tally report as Markdown."""
    rolling_total = metrics.rolling_count(records, now, days=30)
    rolling_corr = metrics.rolling_correction_count(records, now, days=30)
    corr_rate = metrics.interventions_per_100_merges(rolling_corr, merge_count_30d)
    approvals_30d = rolling_total - rolling_corr
    daily_corr = rolling_corr / 30.0
    lpg = metrics.loops_per_governor(active_loop_count, daily_corr)
    class_counts = metrics.by_class(records)
    per_loop = metrics.per_loop_rates(records, merge_count_30d)
    months = metrics.monthly_series(records)
    markers = metrics.model_version_markers(records)

    lines: list[str] = []
    lines.append("# Intervention tally")
    lines.append("")
    lines.append(
        "> Generated by `InterventionTallyLoop` (#10369) — the attention-side "
        "telemetry twin of the escape ledger. Read-only (ADR-0029 Pattern B): "
        "it senses + records human touches (steering, HITL, control-route, "
        "`/hf` CLI) and NEVER gates, blocks, or fixes. `approval` is counted "
        "separately so it never inflates the correction rate."
    )
    lines.append("")
    lines.append(f"_Generated at {now.isoformat()}_")
    lines.append("")

    lines.append("## Headline")
    lines.append("")
    lines.append("| metric | value |")
    lines.append("|---|---|")
    lines.append(f"| interventions (rolling 30d) | {rolling_total} |")
    lines.append(f"| — correction-class | {rolling_corr} |")
    lines.append(f"| — approvals (counted separately) | {approvals_30d} |")
    lines.append(f"| merged changes (rolling 30d) | {merge_count_30d} |")
    lines.append(
        f"| **correction interventions per 100 merges** | **{corr_rate:.2f}** |"
    )
    lines.append(f"| active worker loops | {active_loop_count} |")
    lines.append(f"| **loops per governor** | **{lpg:.1f}** |")
    lines.append(f"| total recorded interventions | {len(records)} |")
    lines.append("")

    lines.append("## By class")
    lines.append("")
    lines.append("| class | count |")
    lines.append("|---|---|")
    for klass in ALL_CLASSES:
        marker = " _(separate)_" if klass == "approval" else ""
        lines.append(f"| {klass}{marker} | {class_counts.get(klass, 0)} |")
    lines.append("")

    lines.append("## Per-loop intervention rate (trust table)")
    lines.append("")
    lines.append(
        "| loop / workflow | total | correction | approval | corr. per 100 merges |"
    )
    lines.append("|---|---|---|---|---|")
    for row in per_loop:
        lines.append(
            f"| {row.loop_or_workflow} | {row.total} | {row.correction} | "
            f"{row.approval} | {row.per_100_merges:.2f} |"
        )
    if not per_loop:
        lines.append("| (no interventions recorded) | 0 | 0 | 0 | 0.00 |")
    lines.append("")

    lines.append("## Monthly series")
    lines.append("")
    lines.append("| month | total | correction | approval | by class |")
    lines.append("|---|---|---|---|---|")
    for m in months:
        by_class = ", ".join(f"{c}={n}" for c, n in sorted(m.by_class.items()))
        lines.append(
            f"| {m.month} | {m.total} | {m.correction} | {m.approval} | "
            f"{by_class or '—'} |"
        )
    if not months:
        lines.append("| (no interventions recorded) | 0 | 0 | 0 | — |")
    lines.append("")

    lines.append("## Model-version markers")
    lines.append("")
    lines.append(
        "> Trust resets on model upgrades — these are the first-seen markers "
        "annotating every trend so a reset is visible, not mysterious."
    )
    lines.append("")
    lines.append("| first seen | model version context |")
    lines.append("|---|---|")
    for ts, model in markers:
        lines.append(f"| {ts} | `{model}` |")
    if not markers:
        lines.append("| — | (none recorded) |")
    lines.append("")

    lines.append("## Recent interventions")
    lines.append("")
    lines.append(
        "| ts | source | class | confidence | loop/workflow | issue/pr | model |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    recent = sorted(records, key=lambda r: r.ts, reverse=True)[:25]
    for r in recent:
        lines.append(
            f"| {r.ts} | {r.source} | {r.intervention_class} | {r.confidence} | "
            f"{r.loop_or_workflow or '—'} | {r.issue_or_pr or '—'} | "
            f"`{r.model_version_context or '—'}` |"
        )
    if not recent:
        lines.append("| (no interventions recorded) | — | — | — | — | — | — |")
    lines.append("")

    lines.append("## Known blind spot")
    lines.append("")
    lines.append(
        "Manual `git` surgery on the repo outside the factory's surfaces is "
        "not sensed in v1 (no capture point). It is the one attention path this "
        "instrument cannot see; treat the rate as a lower bound."
    )
    lines.append("")

    return "\n".join(lines) + "\n"
