"""Plan recovery for ``AgentRunner``.

Extracted VERBATIM from ``src/agent.py`` (god-class decomposition,
Refs #11547) as a mixin.

One concern: getting the approved plan back out of the issue thread — stripping
the planner's framing noise off the plan comment, and the on-disk fallback for
when that comment is gone. Its caller ``_extract_plan_comment`` stays in
``_runner.py``: it reaches ``_strip_plan_noise`` through the literal name
``AgentRunner``, which only resolves where the class is bound.
"""

from __future__ import annotations

import logging
import re
from typing import TYPE_CHECKING

from base_runner import BaseRunner

if TYPE_CHECKING:
    pass


logger = logging.getLogger("hydraflow.agent")


class AgentPlanMixin(BaseRunner):
    """Plan recovery for ``AgentRunner``.

    Inherits ``BaseRunner``: these slices call ``self._execute`` /
    ``self._build_command`` and one delegates to ``super()._verify_quality``,
    so the base has to sit in the MIXIN's own MRO, not only in
    ``AgentRunner``'s. It also keeps the runner-scoped gates enumerating every
    file that holds a spawn site.
    """

    # ------------------------------------------------------------------
    # Collaborator seams — provided by ``AgentRunner.__init__`` or by a sibling
    # mixin. The method declarations are TYPE_CHECKING-only on purpose: a
    # runtime ``...`` body is a real class attribute and would win the MRO
    # over the sibling that really implements it (#11629).
    # ------------------------------------------------------------------

    @staticmethod
    def _strip_plan_noise(raw_comment: str) -> str:
        """Strip boilerplate noise from a planner comment.

        Removes HTML comments, extracts the plan body between
        ``## Implementation Plan`` and the first ``---`` separator
        or end of comment, then drops footer and branch-info lines.
        """
        # Remove HTML comments
        text = re.sub(r"<!--.*?-->", "", raw_comment, flags=re.DOTALL)

        # Extract content after "## Implementation Plan" up to first "---" line or end
        plan_match = re.search(
            r"## Implementation Plan\s*\n(.*?)(?=^---$|\Z)",
            text,
            re.DOTALL | re.MULTILINE,
        )
        if plan_match:
            text = plan_match.group(1)

        # Remove footer and branch-info lines
        lines = text.splitlines()
        cleaned: list[str] = []
        for line in lines:
            stripped = line.strip()
            if "Generated by HydraFlow Planner" in stripped:
                continue
            if stripped.startswith("**Branch:**"):
                continue
            cleaned.append(line)

        return "\n".join(cleaned).strip()

    def _load_plan_fallback(self, issue_number: int) -> str:
        """Attempt to load a saved plan from ``.hydraflow/plans/issue-N.md``.

        Returns the plan text or empty string if not found.
        """
        plan_path = self._config.plans_dir / f"issue-{issue_number}.md"
        if not plan_path.is_file():
            return ""

        logger.warning(
            "No plan comment found for issue #%d — falling back to %s",
            issue_number,
            plan_path,
            extra={"issue": issue_number},
        )
        content = plan_path.read_text()

        # Strip the header/footer added by PlannerRunner._save_plan
        content = re.sub(r"^# Plan for Issue #\d+\s*\n", "", content)
        content = re.sub(r"\n---\n\*\*Summary:\*\*.*$", "", content, flags=re.DOTALL)

        return content.strip()
