from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable

from auto_tighten.models import FileEdit, Measurement


@runtime_checkable
class RatchetAdapter(Protocol):
    ratchet_id: str

    def current(self, repo_root: Path) -> Measurement: ...
    def baseline(self, repo_root: Path) -> Measurement: ...
    def is_tighter(self, a: Measurement, b: Measurement) -> bool: ...
    def weakest(self, a: Measurement, b: Measurement) -> Measurement: ...
    def apply_margin(self, floor: Measurement) -> Measurement: ...
    def render_tightened(
        self, repo_root: Path, value: Measurement
    ) -> list[FileEdit]: ...
    def dedup_key(self, value: Measurement) -> str: ...
