"""Render the static ADR conformance structural map.

This is a **pure, deterministic** view derived from parsing ADRs alone —
it never executes a check and never reads the gitignored conformance
ledger (``adr_conformance.jsonl``). Two reasons this must stay static:

1. ``make arch-regen`` runs in CI, where checks (pytest targets, make
   targets) may not be runnable in that context, and the runner must
   never shell out to execute them just to produce documentation.
2. ``make arch-check`` guards this file for staleness against a pure
   function of committed ADR text; if a runtime loop rewrote it with
   live pass/fail outcomes, every conformance run would look like drift.

Live pass/fail outcomes are reported elsewhere: the gitignored
``adr_conformance.jsonl`` ledger and the ``ADR_CONFORMANCE_UPDATE`` event
payload (see Task 8/9/10 of the ADR conformance contract). This module
answers a different, static question: *for each Accepted ADR, what kind
of enforcement does it claim, and which checks does it cite?*
"""

from __future__ import annotations

from collections import defaultdict

from adr_index import ADR

_HEADER = "# ADR Conformance Map\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.adr_conformance; do not hand-edit -->\n\n"
    "Static structural map of ADR enforcement, derived purely from parsing "
    "Accepted ADRs' `**Enforcement:**` / `**Enforced by:**` fields. This "
    "file never executes a check and carries no live pass/fail outcome — "
    "see `adr_conformance.jsonl` and the `ADR_CONFORMANCE_UPDATE` event for "
    "runtime results.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def _adr_id(adr: ADR) -> str:
    return f"ADR-{adr.number:04d}"


def render_adr_conformance(adrs: list[ADR]) -> str:
    accepted = sorted(
        (a for a in adrs if a.status == "Accepted"), key=lambda a: a.number
    )

    reverse: dict[str, list[str]] = defaultdict(list)
    for a in accepted:
        for check in a.enforced_by:
            reverse[check.as_code_span()].append(_adr_id(a))

    fwd = (
        "## Static Enforcement Map\n\n"
        "| ADR | Enforcement | Cited checks |\n|---|---|---|\n"
    )
    fwd += "\n".join(
        f"| {_adr_id(a)} | {a.enforcement} | "
        f"{', '.join(c.as_code_span() for c in a.enforced_by) or '—'} |"
        for a in accepted
    )

    rev = "\n\n## Check → ADRs it protects\n\n| Check | Protects |\n|---|---|\n"
    rev += "\n".join(
        f"| {check_span} | {', '.join(sorted(set(protects)))} |"
        for check_span, protects in sorted(reverse.items())
    )

    manual = [a for a in accepted if a.enforcement == "manual"]
    man_section = "\n\n## Manual ADRs\n\n"
    if manual:
        man_section += "| ADR | Prose pointer |\n|---|---|\n"
        man_section += "\n".join(
            f"| {_adr_id(a)} | "
            f"{', '.join(c.as_code_span() for c in a.enforced_by) or '—'} |"
            for a in manual
        )
    else:
        man_section += "_(none)_"

    return _HEADER + _PREAMBLE + fwd + rev + man_section + _FOOTER
