"""Render the ADR *enforcement-debt* report.

This is the metric the citation-drift firehose hid (issue #10411): for every
Accepted ADR, does its ``**Enforced by:**`` field resolve to a *real*,
runnable, side-effect-free, *asserting* check — or is the decision only softly
bound (unenforced-decision debt)?

It complements the sibling ``adr_conformance`` generator: that one is a static
*structural* map (which checks each ADR cites); this one is the *debt lens* —
it classifies each Accepted ADR REAL / WEAK / MISSING (see
``adr_conformance.EnforcementClass``) and computes the headline debt count and
percentage.

Unlike the sibling map, this report *resolves* checks against the on-disk tree
(it must, to tell a real asserting test from a hollow one), so it takes
``repo_root`` and its output moves when a cited test's assertion content
changes — the same drift-detection contract ``coverage_matrix.md`` already
carries. Live pass/fail outcomes still live only in the gitignored
``adr_conformance.jsonl`` ledger; this file never executes a check.
"""

from __future__ import annotations

from pathlib import Path

from adr_conformance import (
    EnforcementClass,
    check_is_tautological,
    classify_adr_enforcement,
    resolve_check,
)
from adr_index import ADR, Check

_HEADER = "# ADR Enforcement Debt\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.adr_enforcement; do not hand-edit -->\n\n"
    "Inverts ADR conformance from citation-drift noise to the load-bearing "
    "question: does each Accepted ADR's `**Enforced by:**` resolve to a "
    "*real*, runnable, asserting check, or is the decision unenforced-decision "
    "debt? `REAL` = an `enforced` ADR with a resolving, non-mutating, "
    "*asserting* check. `WEAK` = a `manual` prose pointer, or an `enforced` "
    "ADR whose every resolving check is tautological (green but asserts "
    "nothing). `MISSING` = no `**Enforced by:**` check at all (e.g. a bare "
    "`decision-of-record`). `WEAK` + `MISSING` are the debt.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def _adr_id(adr: ADR) -> str:
    return f"ADR-{adr.number:04d}"


def _checks_span(checks: tuple[Check, ...]) -> str:
    return ", ".join(c.as_code_span() for c in checks) or "—"


def _summary(accepted: list[ADR], by_class: dict[int, EnforcementClass]) -> str:
    total = len(accepted)
    real = sum(1 for a in accepted if by_class[a.number] is EnforcementClass.REAL)
    weak = sum(1 for a in accepted if by_class[a.number] is EnforcementClass.WEAK)
    missing = sum(1 for a in accepted if by_class[a.number] is EnforcementClass.MISSING)
    debt = weak + missing
    enforced = sum(1 for a in accepted if a.enforcement == "enforced")
    manual = sum(1 for a in accepted if a.enforcement == "manual")
    dor = sum(1 for a in accepted if a.enforcement == "decision-of-record")
    pct = f"{100 * debt / total:.1f}%" if total else "0.0%"
    real_pct = f"{100 * real / total:.1f}%" if total else "0.0%"
    return (
        "## Summary\n\n"
        f"- **Accepted ADRs:** {total}\n"
        f"- **REAL** (real asserting enforcement): {real} ({real_pct})\n"
        f"- **WEAK** (prose-only or tautological): {weak}\n"
        f"- **MISSING** (no `**Enforced by:**`): {missing}\n"
        f"- **Unenforced-decision debt** (WEAK + MISSING): **{debt} / {total} "
        f"= {pct}**\n\n"
        "By declared `**Enforcement:**` kind: "
        f"`enforced` {enforced} · `manual` {manual} · "
        f"`decision-of-record` {dor}.\n"
    )


def _classification_table(
    accepted: list[ADR], by_class: dict[int, EnforcementClass]
) -> str:
    out = (
        "\n## Classification\n\n"
        "| ADR | Class | Kind | Enforced by |\n|---|---|---|---|\n"
    )
    out += "\n".join(
        f"| {_adr_id(a)} | {by_class[a.number].value} | {a.enforcement} | "
        f"{_checks_span(a.enforced_by)} |"
        for a in accepted
    )
    return out


def _debt_section(accepted: list[ADR], by_class: dict[int, EnforcementClass]) -> str:
    debt = [
        a
        for a in accepted
        if by_class[a.number] in (EnforcementClass.WEAK, EnforcementClass.MISSING)
    ]
    out = "\n\n## Unenforced-decision debt\n\n"
    if not debt:
        return out + "_(none — every Accepted ADR has a real asserting enforcement)_"
    out += "| ADR | Class | Kind | Pointer |\n|---|---|---|---|\n"
    out += "\n".join(
        f"| {_adr_id(a)} | {by_class[a.number].value} | {a.enforcement} | "
        f"{_checks_span(a.enforced_by)} |"
        for a in debt
    )
    return out


def _tautological_section(accepted: list[ADR], repo_root: Path) -> str:
    """List `enforced` ADRs that cite a *resolving-but-hollow* pytest check.

    These pass ADR-0100's resolution ratchet (the file/node exists) yet the
    node asserts nothing, so the decision can drift while the check stays
    green. Surfaced (not hard-failed) so authors can strengthen them — a
    partial hit here does NOT make the ADR WEAK if a sibling check asserts.
    """
    rows: list[str] = []
    for a in accepted:
        if a.enforcement != "enforced":
            continue
        hollow = [
            c
            for c in a.enforced_by
            if resolve_check(c, repo_root) and check_is_tautological(c, repo_root)
        ]
        for c in hollow:
            rows.append(f"| {_adr_id(a)} | {c.as_code_span()} |")
    out = "\n\n## Weak / tautological enforcements\n\n"
    if not rows:
        return out + "_(none)_"
    out += (
        "Checks that resolve (the node exists) but assert nothing — hollow "
        "guards that stay green while the decision may drift. Strengthen the "
        "cited test or repoint the ADR at one that asserts the invariant.\n\n"
    )
    out += "| ADR | Hollow check |\n|---|---|\n" + "\n".join(rows)
    return out


def render_adr_enforcement(adrs: list[ADR], *, repo_root: Path) -> str:
    accepted = sorted(
        (a for a in adrs if a.status == "Accepted"), key=lambda a: a.number
    )
    by_class = {a.number: classify_adr_enforcement(a, repo_root) for a in accepted}

    body = (
        _HEADER
        + _PREAMBLE
        + _summary(accepted, by_class)
        + _classification_table(accepted, by_class)
        + _debt_section(accepted, by_class)
        + _tautological_section(accepted, repo_root)
        + _FOOTER
    )
    return body
