"""Render the ADR *enforcement-debt* report.

This is the metric the citation-drift firehose hid (issue #10411): for every
Accepted ADR, does its ``**Enforced by:**`` field resolve to a *real*,
runnable, side-effect-free, *asserting* check — or is the decision only softly
bound (unenforced-decision debt)?

It complements the sibling ``adr_conformance`` generator: that one is a static
*structural* map (which checks each ADR cites); this one is the *debt lens* —
it classifies each Accepted ADR REAL / WEAK / MISSING (see
``adr_conformance.EnforcementClass``) and computes the headline debt count and
percentage.

Unlike the sibling map, this report *resolves* checks against the on-disk tree
(it must, to tell a real asserting test from a hollow one), so it takes
``repo_root`` and its output moves when a cited test's assertion content
changes — the same drift-detection contract ``coverage_matrix.md`` already
carries. Live pass/fail outcomes still live only in the gitignored
``adr_conformance.jsonl`` ledger; this file never executes a check.
"""

from __future__ import annotations

from pathlib import Path

from adr_conformance import (
    EnforcementClass,
    adr_is_unattributed,
    check_is_tautological,
    classify_adr_enforcement,
    parse_exemptions,
    resolve_check,
)
from adr_index import ADR, Check


def _parse_exemptions(repo_root: Path) -> dict[int, str]:
    """Return ``{adr_number: justification}`` from the exemptions allow-list.

    Thin fail-open wrapper over ``adr_conformance.parse_exemptions`` — the ONE
    definition of the allow-list path and its entry regex, shared with the
    merge gate in ``tests/architecture/test_adr_enforcement_ratchet.py`` and
    with ``policy.facts`` (#11749). Before the consolidation the regex lived
    here a second time and the two copies were kept in sync by a comment.

    The fail-open ``except OSError`` stays *here*, not in the shared helper:
    this report must still render (identical to its pre-exemption output)
    rather than crash the whole arch pipeline over a missing standards doc —
    the contract the tmp_path unit fixtures rely on. The ratchet keeps the
    strict behaviour, so consolidating did not hand either caller a wider
    exemption lane than it had.
    """
    try:
        return parse_exemptions(repo_root)
    except OSError:
        return {}


_HEADER = "# ADR Enforcement Debt\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.adr_enforcement; do not hand-edit -->\n\n"
    "Inverts ADR conformance from citation-drift noise to the load-bearing "
    "question: does each Accepted ADR's `**Enforced by:**` resolve to a "
    "*real*, runnable, asserting check, or is the decision unenforced-decision "
    "debt? `REAL` = an `enforced` ADR with a resolving, non-mutating, "
    "*asserting* check. `WEAK` = a `manual` prose pointer, or an `enforced` "
    "ADR whose every resolving check is tautological (green but asserts "
    "nothing). `MISSING` = no `**Enforced by:**` check at all (e.g. a bare "
    "`decision-of-record`). `WEAK` + `MISSING` are the debt — except where "
    "the decision is a *justified*, allow-listed process-only exemption "
    "(`docs/standards/adr_enforcement/exemptions.md`): those are excluded from "
    "the outstanding-debt headline, matching the merge gate in "
    "`tests/architecture/test_adr_enforcement_ratchet.py`.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def _adr_id(adr: ADR) -> str:
    return f"ADR-{adr.number:04d}"


def _checks_span(checks: tuple[Check, ...]) -> str:
    return ", ".join(c.as_code_span() for c in checks) or "—"


def _summary(
    accepted: list[ADR],
    by_class: dict[int, EnforcementClass],
    exempted: frozenset[int],
) -> str:
    total = len(accepted)
    real = sum(1 for a in accepted if by_class[a.number] is EnforcementClass.REAL)
    weak = sum(1 for a in accepted if by_class[a.number] is EnforcementClass.WEAK)
    missing = sum(1 for a in accepted if by_class[a.number] is EnforcementClass.MISSING)
    debt_adrs = [
        a
        for a in accepted
        if by_class[a.number] in (EnforcementClass.WEAK, EnforcementClass.MISSING)
    ]
    exempt = sum(1 for a in debt_adrs if a.number in exempted)
    # The load-bearing metric — the same set the ratchet gates on
    # (``_live_debt() - exempted``): WEAK/MISSING that is NOT a justified,
    # allow-listed process-only exemption.
    outstanding = len(debt_adrs) - exempt
    enforced = sum(1 for a in accepted if a.enforcement == "enforced")
    manual = sum(1 for a in accepted if a.enforcement == "manual")
    dor = sum(1 for a in accepted if a.enforcement == "decision-of-record")
    pct = f"{100 * outstanding / total:.1f}%" if total else "0.0%"
    real_pct = f"{100 * real / total:.1f}%" if total else "0.0%"
    return (
        "## Summary\n\n"
        f"- **Accepted ADRs:** {total}\n"
        f"- **REAL** (real asserting enforcement): {real} ({real_pct})\n"
        f"- **WEAK** (prose-only or tautological): {weak}\n"
        f"- **MISSING** (no `**Enforced by:**`): {missing}\n"
        f"- **Justified exemptions** (process-only, allow-listed): {exempt}\n"
        f"- **Outstanding unenforced-decision debt** (non-exempt WEAK + "
        f"MISSING): **{outstanding} / {total} = {pct}**\n\n"
        "By declared `**Enforcement:**` kind: "
        f"`enforced` {enforced} · `manual` {manual} · "
        f"`decision-of-record` {dor}.\n"
    )


def _classification_table(
    accepted: list[ADR],
    by_class: dict[int, EnforcementClass],
    exempted: frozenset[int],
) -> str:
    out = (
        "\n## Classification\n\n"
        "| ADR | Class | Exempt | Kind | Enforced by |\n|---|---|---|---|---|\n"
    )
    out += "\n".join(
        f"| {_adr_id(a)} | {by_class[a.number].value} | "
        f"{'exempt' if a.number in exempted else '—'} | {a.enforcement} | "
        f"{_checks_span(a.enforced_by)} |"
        for a in accepted
    )
    return out


def _debt_section(
    accepted: list[ADR],
    by_class: dict[int, EnforcementClass],
    exemptions: dict[int, str],
) -> str:
    debt = [
        a
        for a in accepted
        if by_class[a.number] in (EnforcementClass.WEAK, EnforcementClass.MISSING)
    ]
    outstanding = [a for a in debt if a.number not in exemptions]
    exempt = [a for a in debt if a.number in exemptions]

    out = "\n\n## Unenforced-decision debt\n\n### Outstanding (non-exempt)\n\n"
    if not outstanding:
        out += (
            "_(none — every non-exempt Accepted ADR has a real asserting enforcement)_"
        )
    else:
        out += "| ADR | Class | Kind | Pointer |\n|---|---|---|---|\n"
        out += "\n".join(
            f"| {_adr_id(a)} | {by_class[a.number].value} | {a.enforcement} | "
            f"{_checks_span(a.enforced_by)} |"
            for a in outstanding
        )

    out += "\n\n### Justified exemptions (process-only, allow-listed)\n\n"
    if not exempt:
        out += "_(none)_"
    else:
        out += (
            "Allow-listed in `docs/standards/adr_enforcement/exemptions.md` as "
            "genuinely process-only — no machine-checkable invariant — so "
            "excluded from the outstanding-debt headline above.\n\n"
            "| ADR | Class | Kind | Justification |\n|---|---|---|---|\n"
        )
        out += "\n".join(
            f"| {_adr_id(a)} | {by_class[a.number].value} | {a.enforcement} | "
            f"{exemptions[a.number]} |"
            for a in exempt
        )
    return out


def _tautological_section(accepted: list[ADR], repo_root: Path) -> str:
    """List `enforced` ADRs that cite a *resolving-but-hollow* pytest check.

    These pass ADR-0100's resolution ratchet (the file/node exists) yet the
    node asserts nothing, so the decision can drift while the check stays
    green. Surfaced (not hard-failed) so authors can strengthen them — a
    partial hit here does NOT make the ADR WEAK if a sibling check asserts.
    """
    rows: list[str] = []
    for a in accepted:
        if a.enforcement != "enforced":
            continue
        hollow = [
            c
            for c in a.enforced_by
            if resolve_check(c, repo_root) and check_is_tautological(c, repo_root)
        ]
        for c in hollow:
            rows.append(f"| {_adr_id(a)} | {c.as_code_span()} |")
    out = "\n\n## Weak / tautological enforcements\n\n"
    if not rows:
        return out + "_(none)_"
    out += (
        "Checks that resolve (the node exists) but assert nothing — hollow "
        "guards that stay green while the decision may drift. Strengthen the "
        "cited test or repoint the ADR at one that asserts the invariant.\n\n"
    )
    out += "| ADR | Hollow check |\n|---|---|\n" + "\n".join(rows)
    return out


def _unattributed_section(accepted: list[ADR], repo_root: Path) -> str:
    """List REAL ADRs whose enforcing tests never name them (#10861).

    These resolve (the cited file exists) and assert, so they classify REAL —
    yet the test's text does not reference the ADR number, so "REAL" here means
    only "names a file that exists", not "names a check that tests this ADR".
    Advisory, exactly like the tautological section: surfaced so authors can add
    the ADR number to the enforcing test (or repoint it), and ratcheted
    shrink-only in ``tests/test_adr_enforcement_completeness.py`` — never a hard
    downgrade of the ADR's class.
    """
    rows = [
        f"| {_adr_id(a)} | {_checks_span(a.enforced_by)} |"
        for a in accepted
        if adr_is_unattributed(a, repo_root)
    ]
    out = "\n\n## Unattributed enforcements\n\n"
    if not rows:
        return out + "_(none)_"
    out += (
        "REAL ADRs whose cited test resolves and asserts, but whose text never "
        "names the ADR — so the check need not relate to the decision it "
        "enforces. Add the ADR number (e.g. `ADR-0123`) to the enforcing test, "
        "or repoint the ADR at one that names it. Advisory: this does NOT change "
        "the REAL/WEAK/MISSING class above.\n\n"
    )
    out += "| ADR | Enforcement |\n|---|---|\n" + "\n".join(rows)
    return out


def render_adr_enforcement(adrs: list[ADR], *, repo_root: Path) -> str:
    accepted = sorted(
        (a for a in adrs if a.status == "Accepted"), key=lambda a: a.number
    )
    by_class = {a.number: classify_adr_enforcement(a, repo_root) for a in accepted}
    exemptions = _parse_exemptions(repo_root)
    exempted = frozenset(exemptions)

    body = (
        _HEADER
        + _PREAMBLE
        + _summary(accepted, by_class, exempted)
        + _classification_table(accepted, by_class, exempted)
        + _debt_section(accepted, by_class, exemptions)
        + _tautological_section(accepted, repo_root)
        + _unattributed_section(accepted, repo_root)
        + _FOOTER
    )
    return body
