"""Render the bidirectional ADR ↔ module cross-reference."""

from __future__ import annotations

from collections import defaultdict

from adr_index import ADR
from arch._models import ADRRefIndex

_HEADER = "# ADR Cross-Reference\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.adr_cross_reference; do not hand-edit -->\n\n"
    "Bidirectional index between ADRs and the source modules they cite. "
    'Powers "Why this exists" backlinks across the site.\n\n'
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def render_adr_cross_reference(idx: ADRRefIndex, adrs: list[ADR] | None = None) -> str:
    forward = sorted(idx.adr_to_modules, key=lambda r: r.adr_id)
    reverse: dict[str, list[str]] = defaultdict(list)
    for r in forward:
        for m in r.cited_modules:
            reverse[m].append(r.adr_id)

    # ADR-0100: surface which checks enforce each ADR alongside the module
    # citations. Keyed by ADR number so lookups work regardless of adrs'
    # ordering; missing/omitted `adrs` renders "—" for every row.
    enforced_by_raw: dict[str, str] = {}
    for a in adrs or []:
        adr_id = f"ADR-{a.number:04d}"
        enforced_by_raw[adr_id] = (
            ", ".join(c.as_code_span() for c in a.enforced_by) or "—"
        )

    fwd = "## ADR → Modules\n\n| ADR | Modules cited | Enforced by |\n|---|---|---|\n"
    fwd += "\n".join(
        f"| {r.adr_id} | {', '.join(f'`{m}`' for m in r.cited_modules) or '—'} | "
        f"{enforced_by_raw.get(r.adr_id, '—')} |"
        for r in forward
    )

    rev = "\n\n## Module → ADRs\n\n| Module | Cited by |\n|---|---|\n"
    rev += "\n".join(
        f"| `{m}` | {', '.join(sorted(set(adrs)))} |"
        for m, adrs in sorted(reverse.items())
    )

    return _HEADER + _PREAMBLE + fwd + rev + _FOOTER
