"""Render the event bus topology as a publishers/subscribers table.

HydraFlow's ``EventBus`` fans out **every** published event to **all**
subscribers — ``subscribe()`` / ``subscription()`` take no event type, so
subscribers are global, not per-``EventType``. The Subscribers column reflects
that: every live event shows ``★ all (fan-out)`` and the actual fan-out
consumers are listed once in the preamble. An event is flagged ⚠️ (likely dead)
only when it is a declared ``EventType`` with no publisher and is not on the
live-only ``EPHEMERAL_EVENT_TYPES`` allowlist.
"""

from __future__ import annotations

from arch._models import EventBusTopology

_HEADER = "# Event Bus Topology\n\n"
_INTRO = (
    "<!-- generated by arch.generators.event_bus; do not hand-edit -->\n\n"
    "HydraFlow's `EventBus` fans out **every** published event to **all** "
    "subscribers: `subscribe()` / `subscription()` take no event type "
    "(`src/events.py`), so subscribers are global — one queue drains the whole "
    "bus — not per-`EventType`. The Subscribers column shows `★ all (fan-out)` "
    "for every live event; the fan-out consumers are listed below. An event is "
    "flagged ⚠️ (likely dead) only when it is a declared `EventType` with **no "
    "publisher** (the live-only `EPHEMERAL_EVENT_TYPES` allowlist is exempt).\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"

_FANOUT_CELL = "★ all (fan-out)"
_NONE = "—"


def _consumers_block(global_subscribers: list[str]) -> str:
    if not global_subscribers:
        return "**Fan-out consumers:** _(none discovered)_\n\n"
    lines = "\n".join(f"- `{s}`" for s in global_subscribers)
    return (
        f"**Fan-out consumers** (each receives every published event):\n\n{lines}\n\n"
    )


def render_event_bus(topo: EventBusTopology) -> str:
    if not topo.events:
        return _HEADER + _INTRO + "_(no events discovered)_\n" + _FOOTER

    has_consumers = bool(topo.global_subscribers)
    rows = []
    for e in topo.events:
        is_dead = not e.publishers and not e.ephemeral
        flag = " ⚠️" if is_dead else ""
        pubs = "<br>".join(f"`{p}`" for p in e.publishers) or _NONE
        subs = _FANOUT_CELL if (has_consumers and not is_dead) else _NONE
        rows.append(f"| **{e.event}**{flag} | {pubs} | {subs} |")

    table = "| Event | Publishers | Subscribers |\n|---|---|---|\n" + "\n".join(rows)
    return (
        _HEADER + _INTRO + _consumers_block(topo.global_subscribers) + table + _FOOTER
    )
