"""Render the event bus topology as a publishers/subscribers table.

HydraFlow's ``EventBus`` fans out **every** published event to all *fan-out*
subscribers — an argless ``subscribe()`` / ``subscription()`` returns a queue
that receives everything. Since ADR-0114 (#10660) a subscriber MAY instead pass
an optional per-type filter, ``subscribe(types={EventType.X, ...})``, so its
queue only receives the types it asked for. The Subscribers column shows
``★ all (fan-out)`` for every live event, plus any typed consumer that filters
on that specific event. Fan-out and typed consumers are listed once in the
preamble. An event is flagged ⚠️ (likely dead) only when it is a declared
``EventType`` with no publisher and is not on the live-only
``EPHEMERAL_EVENT_TYPES`` allowlist.
"""

from __future__ import annotations

from arch._models import EventBusTopology, TypedSubscriber

_HEADER = "# Event Bus Topology\n\n"
_INTRO = (
    "<!-- generated by arch.generators.event_bus; do not hand-edit -->\n\n"
    "HydraFlow's `EventBus` fans out **every** published event to all *fan-out* "
    "subscribers: an argless `subscribe()` / `subscription()` (`src/events.py`) "
    "returns a queue that drains the whole bus. Since ADR-0114 (#10660) a "
    "subscriber MAY instead pass an optional per-type filter — "
    "`subscribe(types={EventType.X, ...})` — so its queue only receives those "
    "types (filtered at publish time, so an ignored high-volume type never "
    "fills its bounded slots). The Subscribers column shows `★ all (fan-out)` "
    "for every live event, plus any typed consumer that filters on it. An event "
    "is flagged ⚠️ (likely dead) only when it is a declared `EventType` with "
    "**no publisher** (the live-only `EPHEMERAL_EVENT_TYPES` allowlist is "
    "exempt).\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"

_FANOUT_CELL = "★ all (fan-out)"
_NONE = "—"


def _consumers_block(global_subscribers: list[str]) -> str:
    if not global_subscribers:
        return "**Fan-out consumers:** _(none discovered)_\n\n"
    lines = "\n".join(f"- `{s}`" for s in global_subscribers)
    return (
        f"**Fan-out consumers** (each receives every published event):\n\n{lines}\n\n"
    )


def _typed_consumers_block(typed_subscribers: list[TypedSubscriber]) -> str:
    if not typed_subscribers:
        return ""
    lines = "\n".join(
        f"- `{t.subscriber}` — {', '.join(t.types) if t.types else '_(unresolved)_'}"
        for t in typed_subscribers
    )
    return (
        "**Typed consumers** (ADR-0114 — each receives only the listed "
        f"`EventType`s):\n\n{lines}\n\n"
    )


def _typed_by_event(typed_subscribers: list[TypedSubscriber]) -> dict[str, list[str]]:
    """Invert typed subscribers into ``event name -> [subscriber ids]``."""
    by_event: dict[str, list[str]] = {}
    for t in typed_subscribers:
        for ev in t.types:
            by_event.setdefault(ev, []).append(t.subscriber)
    return by_event


def render_event_bus(topo: EventBusTopology) -> str:
    if not topo.events:
        return _HEADER + _INTRO + "_(no events discovered)_\n" + _FOOTER

    has_consumers = bool(topo.global_subscribers)
    typed_by_event = _typed_by_event(topo.typed_subscribers)
    rows = []
    for e in topo.events:
        is_dead = not e.publishers and not e.ephemeral
        flag = " ⚠️" if is_dead else ""
        pubs = "<br>".join(f"`{p}`" for p in e.publishers) or _NONE
        parts: list[str] = []
        if has_consumers and not is_dead:
            parts.append(_FANOUT_CELL)
        if not is_dead:
            parts.extend(f"`{s}`" for s in typed_by_event.get(e.event, []))
        subs = "<br>".join(parts) if parts else _NONE
        rows.append(f"| **{e.event}**{flag} | {pubs} | {subs} |")

    table = "| Event | Publishers | Subscribers |\n|---|---|---|\n" + "\n".join(rows)
    return (
        _HEADER
        + _INTRO
        + _consumers_block(topo.global_subscribers)
        + _typed_consumers_block(topo.typed_subscribers)
        + table
        + _FOOTER
    )
