"""Render the gauntlet-calibration report (``docs/arch/generated/gauntlet-calibration.md``).

This is the shared calibration instrument surface: the judge-independence budget
(#10371) and — when it lands — the sampled-adversarial re-audit (#10367) both
report into this one file. The generated artifact is deterministic-from-source
by design: it documents the *instrument* (what each metric means, the control-
limit method, the ledger schema) rather than embedding volatile runtime counts.

Runtime telemetry belongs on the live dashboard panel (``/api/diagnostics/
gauntlet-calibration``), NOT in a git-committed arch artifact — a data-bearing
generated doc would drift every time ``DiagramLoop`` regenerated it against a
populated ``data_root`` while CI regenerated the empty version from a clean
checkout (the factory-on-stale-main drift footgun).

``render_gauntlet_calibration`` therefore accepts an optional ``metrics`` dict
(the shape ``judge_independence.calibration_metrics`` returns): the dashboard
passes live metrics to render populated tables; the arch runner passes ``None``
to emit the deterministic instrument-spec version.
"""

from __future__ import annotations

from typing import Any

_HEADER = "# Gauntlet Calibration\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.gauntlet_calibration; do not hand-edit -->\n\n"
    "The empirical calibration picture for the factory's evidence path — how "
    "much independent scrutiny merged changes actually carried, and how loudly "
    "the evidence path fails when a judge is unavailable. Shared instrument "
    "surface for the judge-independence budget + fail-visible dispatch (#10371) "
    "and the sampled-adversarial re-audit (#10367).\n\n"
    "**This artifact is deterministic-from-source (instrument spec + schema).** "
    "Live values render on the dashboard panel (`/api/diagnostics/"
    "gauntlet-calibration`), which reads the append-only ledger at "
    "`<data_root>/diagnostics/fail_open_ledger.jsonl`.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


_METRIC_DEFS = (
    "## Metrics\n\n"
    "| metric | definition |\n|---|---|\n"
    "| % classed merges with independent verdict | of changes in a blast-radius "
    "class (structural / security / migration / self-modification), the share "
    "whose post-verify verdict came from a model family OUTSIDE the implementing "
    "roster |\n"
    "| fail-open rate | judge-unavailable → work-passed events per day; a "
    "Shewhart c-chart control limit (`cbar + 3*sqrt(cbar)`) flags spikes and "
    "`FailOpenMonitorLoop` files a `hydraflow-find` above-limit |\n"
    "| independence-unavailable rate | classed changes that proceeded on a "
    "same-family verdict (or self-mod changes escalated to HITL) because no "
    "independent family was configured/reachable — degraded, never silent |\n"
    "| disagreement-by-family | where an independent judge dissents from the "
    "sibling verdicts, partitioned by family — the empirical measure of how "
    "much correlated blindness the budget is catching |\n\n"
)

_SELF_MOD_NOTE = (
    "## Fail-closed for self-modification\n\n"
    "The self-modification class (changes touching the gauntlet, gates, "
    "detectors, merge policy, or this policy itself — including the classifier) "
    "is the highest class: a missing verdict on the machinery that produces "
    "verdicts is a STOP, not a degraded pass. A fail-open or a missing "
    "independent verdict on a self-mod change blocks the merge and escalates to "
    "HITL (feature-flagged: `HYDRAFLOW_JUDGE_SELF_MOD_FAIL_CLOSED`). All other "
    "classes remain fail-open but ledgered and alarmed.\n\n"
)


def _pct_table(metrics: dict[str, Any] | None) -> str:
    if not metrics:
        return (
            "## Current observations\n\n"
            "_(no observations recorded yet — live values render on the "
            "dashboard panel)_\n\n"
        )
    lines = [
        "## Current observations\n",
        "| measure | value |",
        "|---|---|",
        f"| classed verdicts | {metrics.get('classed_verdicts', 0)} |",
        f"| independent verdicts | {metrics.get('independent_verdicts', 0)} |",
        f"| % carrying independent verdict | {metrics.get('pct_independent', 0)} |",
        f"| fail-open total | {metrics.get('fail_open_total', 0)} |",
        f"| fail-open control limit (UCL) | {metrics.get('fail_open_ucl', 0)} |",
        f"| fail-open rate breached | {metrics.get('fail_open_rate_breached', False)} |",
        "| independence-unavailable total | "
        f"{metrics.get('independence_unavailable_total', 0)} |",
        "",
    ]
    return "\n".join(lines) + "\n"


def _disagreement_table(metrics: dict[str, Any] | None) -> str:
    header = "## Disagreement by family\n\n| family | independent verdicts | dissents |\n|---|---|---|\n"
    by_family = (metrics or {}).get("disagreement_by_family", {}) or {}
    if not by_family:
        return header + "| _(none yet)_ | 0 | 0 |\n\n"
    rows = "\n".join(
        f"| {fam} | {v.get('verdicts', 0)} | {v.get('dissents', 0)} |"
        for fam, v in sorted(by_family.items())
    )
    return header + rows + "\n\n"


def render_gauntlet_calibration(metrics: dict[str, Any] | None = None) -> str:
    """Render the gauntlet-calibration markdown report.

    ``metrics`` is the dict from ``judge_independence.calibration_metrics`` (live
    dashboard render), or ``None`` for the deterministic instrument-spec version
    the arch runner emits.
    """
    return (
        _HEADER
        + _PREAMBLE
        + _METRIC_DEFS
        + _SELF_MOD_NOTE
        + _pct_table(metrics)
        + _disagreement_table(metrics)
        + _FOOTER
    )
