"""Render the requirements traceability matrix (CH-5, #9733).

Req-ID → issues → PRs → commits → test evidence → approval, per the
regulated-traceability expectations sketched in issue #9733 (design
controls / traceability matrices). Two deterministic sources:

- ``Req-ID:`` lines in the most recent PR-squash-merge commits reachable
  from HEAD (collected by ``arch.runner`` via ``git log`` and parsed here
  by :func:`parse_trace_commits`), and
- ``Req-ID:`` references in *docstrings* under ``tests/`` (module, class,
  and function docstrings only — string literals in test code are NOT
  evidence, so synthetic IDs in test fixtures cannot pollute the matrix).

Unthreaded work appears as a single aggregate ``(untraced)`` row exposing
only an integer percentage (``<!-- untraced-pct: NN -->``). Raw counts are
deliberately omitted: they change on every merge and would churn the
arch drift check, whereas the ceiled percentage stays put until adoption
meaningfully moves. The ``traceability`` disturbance dimension reads the
marker and ratchets the fraction — it may only shrink.
"""

from __future__ import annotations

import ast
import math
import re
import subprocess
from pathlib import Path

from arch._models import TraceCommitInfo
from traceability import normalize_req_id

#: How many PR-squash-merge commits form the adoption-measurement window.
TRACE_WINDOW = 500

_HEADER = "# Requirements Traceability Matrix\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.traceability_matrix; do not hand-edit -->\n\n"
    "Req-ID → issues → PRs → commits → test evidence → approval (CH-5, #9733).\n"
    "Requirement IDs are declared on issues as a `req:<id>` label or a\n"
    "`Req-ID:` body line, carried into plan comments, PR bodies, and commit\n"
    f"trailers. Sources: `Req-ID:` lines in the last ≤{TRACE_WINDOW} PR-merge "
    "commits\nreachable from HEAD, plus `Req-ID:` references in test "
    "docstrings under\n`tests/`. Enforcement is a ratchet, not a gate: "
    "Req-IDs are mandatory only\nfor the regulated change class "
    "(`HydraFlowConfig.regulated_labels`, default\nempty).\n\n"
)
_FOOTER = "\n{{ARCH_FOOTER}}\n"

_PR_SUFFIX_RE = re.compile(r"\(#(?P<pr>\d+)\)\s*$")
# Inline form — docstrings reference requirements mid-sentence by design
# ("Verifies Req-ID: X end-to-end").
_REQ_ID_REF_RE = re.compile(
    r"Req-ID:[ \t]*(?P<req_id>[A-Za-z0-9][A-Za-z0-9._/-]{0,63})"
)
# Line-anchored form for commit messages: real trailers are line-initial
# (GitHub squash-mangling at worst prefixes a `* ` bullet), whereas prose
# ABOUT the threading feature mentions the key mid-sentence and must not
# mint a requirement ID.
_REQ_ID_TRAILER_RE = re.compile(
    r"^\s*\*?\s*Req-ID:[ \t]*(?P<req_id>[A-Za-z0-9][A-Za-z0-9._/-]{0,63})",
    re.MULTILINE,
)
_ISSUE_REF_RE = re.compile(
    r"\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(?P<issue>\d+)", re.IGNORECASE
)
_APPROVAL_RE = re.compile(
    r"^\s*\*?\s*(?:Reviewed|Approved)-by:[ \t]*(?P<who>.+?)\s*$",
    re.IGNORECASE | re.MULTILINE,
)


def parse_trace_commits(
    raw: str, *, window: int = TRACE_WINDOW
) -> list[TraceCommitInfo]:
    """Parse ``git log --pretty=format:%H%x1f%s%x1f%B%x1e`` output.

    Keeps only PR-squash-merge-shaped commits (subject ending in
    ``(#NNNN)``) — branch work-in-progress commits are not population, so
    an open PR's own commits cannot move the matrix. Newest-first order is
    preserved; the population is capped at *window*.
    """
    commits: list[TraceCommitInfo] = []
    for record in raw.split("\x1e"):
        parts = record.strip("\n").split("\x1f", 2)
        if len(parts) < 3:
            continue
        sha, subject, body = parts
        sha = sha.strip()
        match = _PR_SUFFIX_RE.search(subject)
        if not match or not sha:
            continue
        req_ids: list[str] = []
        for m in _REQ_ID_TRAILER_RE.finditer(body):
            req_id = normalize_req_id(m.group("req_id"))
            if req_id is not None and req_id not in req_ids:
                req_ids.append(req_id)
        issue_refs: list[int] = []
        for m in _ISSUE_REF_RE.finditer(body):
            issue = int(m.group("issue"))
            if issue not in issue_refs:
                issue_refs.append(issue)
        approvals = [m.group("who") for m in _APPROVAL_RE.finditer(body)]
        commits.append(
            TraceCommitInfo(
                sha=sha,
                subject=subject,
                pr_number=int(match.group("pr")),
                req_ids=req_ids,
                issue_refs=issue_refs,
                approvals=approvals,
            )
        )
        if len(commits) >= window:
            break
    return commits


#: Timeout for the git subprocess calls below — same rationale as
#: ``arch.runner._run`` (thread-pool exhaustion guard, PR #8454 class).
_GIT_TIMEOUT_S = 60


def _run_git(repo_root: Path, *args: str) -> str | None:
    """Run one git command; ``None`` on any failure (rc != 0, timeout, no git)."""
    try:
        res = subprocess.run(
            ["git", *args],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=False,
            timeout=_GIT_TIMEOUT_S,
        )
    except (OSError, subprocess.TimeoutExpired, subprocess.SubprocessError):
        return None
    if res.returncode != 0:
        return None
    return res.stdout


def _history_is_recomputable(repo_root: Path) -> bool:
    """True when *repo_root* has trustworthy git history for a recompute.

    False for: git missing/failed, *repo_root* not the top level of a git
    work tree, or a shallow clone (CI test checkouts default to
    fetch-depth 1 — a truncated window would misreport the fraction).
    """
    probe = _run_git(
        repo_root, "rev-parse", "--show-toplevel", "--is-shallow-repository"
    )
    if probe is None:
        return False
    lines = probe.strip().splitlines()
    if len(lines) != 2 or lines[1].strip() == "true":
        return False
    try:
        return Path(lines[0]).resolve() == Path(repo_root).resolve()
    except OSError:
        return False


def collect_trace_commits(repo_root: Path) -> list[TraceCommitInfo] | None:
    """Collect the traceability population from *repo_root*'s git history.

    Shared by the generator (``arch.runner``), the ratchet-baseline sync
    (``sync_traceability_baseline``) and the ``TraceabilityDetector``'s
    marker verification, so all three compute the untraced fraction through
    ONE code path — the committed ``<!-- untraced-pct: NN -->`` marker is
    display-only and must be independently recomputable (CH-5 convergence
    review finding 3).

    Returns ``None`` when history is unavailable or untrustworthy for a
    recompute (see :func:`_history_is_recomputable`). Returns ``[]`` when
    history IS available but parses to zero PR-squash-merge commits —
    callers must treat that as a generation regression when the ratchet
    baseline is nonzero, never as 0% untraced.
    """
    if not _history_is_recomputable(repo_root):
        return None
    fmt = "%H%x1f%s%x1f%B%x1e"
    raw = _run_git(repo_root, "log", f"-n{TRACE_WINDOW * 6}", f"--pretty=format:{fmt}")
    if raw is None:
        return None
    return parse_trace_commits(raw)


def _docstring_req_ids(tree: ast.AST) -> list[str]:
    """Collect Req-ID references from module/class/function docstrings."""
    refs: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(
            node, ast.Module | ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef
        ):
            continue
        doc = ast.get_docstring(node, clean=False)
        if not doc or "Req-ID" not in doc:
            continue
        for m in _REQ_ID_REF_RE.finditer(doc):
            req_id = normalize_req_id(m.group("req_id"))
            if req_id is not None:
                refs.append(req_id)
    return refs


def _scan_test_evidence(repo_root: Path) -> dict[str, list[str]]:
    """Map Req-ID → sorted test file paths whose docstrings reference it."""
    evidence: dict[str, set[str]] = {}
    tests_dir = repo_root / "tests"
    if not tests_dir.is_dir():
        return {}
    for path in sorted(tests_dir.rglob("*.py")):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if "Req-ID" not in text:
            continue  # cheap pre-filter before the AST parse
        try:
            tree = ast.parse(text)
        except SyntaxError:
            continue
        rel = path.relative_to(repo_root).as_posix()
        for req_id in _docstring_req_ids(tree):
            evidence.setdefault(req_id, set()).add(rel)
    return {req_id: sorted(paths) for req_id, paths in evidence.items()}


def untraced_pct(commits: list[TraceCommitInfo]) -> int:
    """Ceiled integer % of window commits with no Req-ID (0 for empty window).

    ``ceil`` keeps the metric conservative: it stays at 100 until adoption
    is substantial enough to genuinely move a percentage point, so a lone
    traced commit aging out of the window cannot flap the ratchet.

    Public because the marker-verification recompute (baseline sync +
    ``TraceabilityDetector``) must share the generator's exact rounding.
    """
    if not commits:
        return 0
    untraced = sum(1 for c in commits if not c.req_ids)
    return math.ceil(100 * untraced / len(commits))


def _requirement_rows(
    commits: list[TraceCommitInfo], evidence: dict[str, list[str]]
) -> list[str]:
    by_req: dict[str, list[TraceCommitInfo]] = {}
    for commit in commits:
        for req_id in commit.req_ids:
            by_req.setdefault(req_id, []).append(commit)

    rows: list[str] = []
    for req_id in sorted(set(by_req) | set(evidence)):
        traced = by_req.get(req_id, [])
        issues = sorted({i for c in traced for i in c.issue_refs})
        prs = sorted({c.pr_number for c in traced})
        shas = [f"`{c.sha[:7]}`" for c in traced]
        approvals: list[str] = []
        for commit in traced:
            for who in commit.approvals:
                if who not in approvals:
                    approvals.append(who)
        tests = [f"`{p}`" for p in evidence.get(req_id, [])]
        rows.append(
            "| {req} | {issues} | {prs} | {commits} | {tests} | {approvals} |".format(
                req=req_id,
                issues=", ".join(f"#{i}" for i in issues) or "—",
                prs=", ".join(f"#{p}" for p in prs) or "—",
                commits=", ".join(shas) or "—",
                tests=", ".join(tests) or "—",
                approvals=", ".join(approvals) or "—",
            )
        )
    return rows


def render_traceability_matrix(
    commits: list[TraceCommitInfo],
    *,
    repo_root: Path,
) -> str:
    """Return the traceability matrix as deterministic markdown."""
    evidence = _scan_test_evidence(repo_root)
    rows = _requirement_rows(commits, evidence)
    pct = untraced_pct(commits)

    chunks: list[str] = ["## Section 1: Requirements\n"]
    if rows:
        chunks.append("| Req-ID | Issues | PRs | Commits | Test evidence | Approval |")
        chunks.append("|---|---|---|---|---|---|")
        chunks.extend(rows)
    else:
        chunks.append(
            "_(no requirement IDs threaded yet — declare one with a `req:<id>` "
            "label or a `Req-ID:` line in an issue body)_"
        )
    chunks.append("")
    chunks.append("## Section 2: Untraced changes\n")
    chunks.append(
        "Adoption ratchet: the fraction of window commits carrying no "
        "`Req-ID:`\nline. Pinned by the `traceability` disturbance dimension "
        "(`disturbance/baselines/traceability.yaml`) — it may only shrink. "
        "Raw counts are\nomitted on purpose; see the module docstring."
    )
    chunks.append("")
    chunks.append(f"<!-- untraced-pct: {pct} -->")
    chunks.append("")
    chunks.append("| Scope | Untraced |")
    chunks.append("|---|---|")
    chunks.append(
        f"| (untraced) — PR-merge commits in the window (≤{TRACE_WINDOW}) "
        f"without a `Req-ID:` line | {pct}% |"
    )
    return _HEADER + _PREAMBLE + "\n".join(chunks) + _FOOTER
