"""Local materialization for HydraFlow-format repository bootstrap drafts."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from onboarding.models import BootstrapSpec

METHODOLOGY_REF = "docs/methodology/onboarding-hydraflow-format-repos.md"


@dataclass(frozen=True)
class MaterializedFile:
    """A file written by the templating service."""

    path: str
    bytes_written: int


@dataclass(frozen=True)
class MaterializeResult:
    """Result of writing a draft repository to disk."""

    root: Path
    files: tuple[MaterializedFile, ...]
    events: tuple[dict[str, str], ...]


class MaterializeError(RuntimeError):
    """Raised when local materialization cannot safely proceed."""


def package_name_for(spec: BootstrapSpec) -> str:
    """Return the import package name for *spec*."""

    if spec.package_name:
        candidate = spec.package_name.strip().lower().replace("-", "_")
    else:
        candidate = spec.name.replace("-", "_")
    if not re.fullmatch(r"[a-z][a-z0-9_]{1,99}", candidate):
        raise MaterializeError("package_name must be a valid Python package name")
    return candidate


def materialize_repository(spec: BootstrapSpec, parent_dir: Path) -> MaterializeResult:
    """Write the deterministic bootstrap kernel for *spec* under *parent_dir*."""

    parent = parent_dir.expanduser().resolve()
    target = parent / spec.name
    if target.exists() and any(target.iterdir()):
        raise MaterializeError(
            f"target directory already exists and is not empty: {target}"
        )
    target.mkdir(parents=True, exist_ok=True)

    package_name = package_name_for(spec)
    generated_at = datetime.now(UTC).isoformat()
    context = _TemplateContext(
        spec=spec, package_name=package_name, generated_at=generated_at
    )
    files = _render_files(context)
    written: list[MaterializedFile] = []
    for relative_path, content in files.items():
        destination = target / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        data = content.encode()
        destination.write_bytes(data)
        written.append(MaterializedFile(path=relative_path, bytes_written=len(data)))

    return MaterializeResult(
        root=target,
        files=tuple(written),
        events=(
            {"level": "info", "message": "materialized invariant kernel"},
            {"level": "info", "message": f"wrote {len(written)} files"},
        ),
    )


@dataclass(frozen=True)
class _TemplateContext:
    spec: BootstrapSpec
    package_name: str
    generated_at: str

    @property
    def cli_entry(self) -> str:
        return self.spec.name.replace("-", "_")

    @property
    def project_title(self) -> str:
        return self.spec.name.replace("-", " ").title()

    @property
    def safety_block(self) -> str:
        if not self.spec.safety_guards:
            return "- Keep V1 deliberately small and covered by tests."
        return "\n".join(f"- {guard}" for guard in self.spec.safety_guards)


def wizard_frontmatter(ctx: _TemplateContext) -> str:
    """Return the wizard-draft frontmatter required by the factory handshake."""

    return (
        "---\n"
        "status: wizard-draft\n"
        "generated_by: hydraflow-wizard\n"
        f"generated_at: {ctx.generated_at}\n"
        "methodology_refs:\n"
        f"  - {METHODOLOGY_REF}\n"
        "needs_refinement: true\n"
        "refinement_hints:\n"
        "  - cross_repo_consistency\n"
        "  - adr_review\n"
        "  - plan_02_task_expansion\n"
        "---\n\n"
    )


def _render_files(ctx: _TemplateContext) -> dict[str, str]:
    package = ctx.package_name
    return {
        ".env.example": f"# {ctx.project_title}\nLOG_LEVEL=INFO\n",
        ".gitignore": ".venv/\n__pycache__/\n.coverage\n.pytest_cache/\ndist/\n",
        "Makefile": _makefile(ctx),
        "pyproject.toml": _pyproject(ctx),
        "README.md": _readme(ctx),
        "CLAUDE.md": _claude_md(ctx),
        f"src/{package}/__init__.py": '"""Project package generated by HydraFlow onboarding."""\n',
        f"src/{package}/cli.py": _cli(ctx),
        "tests/unit/test_smoke.py": _smoke_test(ctx),
        ".github/workflows/quality.yml": _quality_workflow(ctx),
        ".github/ISSUE_TEMPLATE/bug.md": _issue_template(ctx, "Bug report"),
        ".github/ISSUE_TEMPLATE/feature.md": _issue_template(ctx, "Feature request"),
        ".github/PULL_REQUEST_TEMPLATE.md": _pull_request_template(ctx),
        "docs/adr/README.md": "# ADRs\n\n- [ADR-0001](0001-initial-architecture.md) - Initial architecture\n",
        "docs/adr/0001-initial-architecture.md": _adr(ctx),
        "docs/standards/testing.md": "# Testing Standard\n\nEvery behavior change gets a focused automated test.\n",
        "docs/wiki/index.md": _wiki(ctx),
        "scripts/__init__.py": '"""Project maintenance scripts."""\n',
        "scripts/prep.py": _prep_script(ctx),
        "scripts/setup_branch_protection.py": _branch_protection_script(),
        "docs/specs/bootstrap-spec.md": wizard_frontmatter(ctx) + _spec_doc(ctx),
        "docs/plans/plan-01-bootstrap.md": wizard_frontmatter(ctx) + _plan_doc(ctx),
    }


def _pyproject(ctx: _TemplateContext) -> str:
    return f"""[project]
name = "{ctx.spec.name}"
version = "0.1.0"
description = "{ctx.spec.description}"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
{ctx.cli_entry} = "{ctx.package_name}.cli:main"

[project.optional-dependencies]
dev = [
  "pytest>=8",
  "pytest-cov>=5",
  "ruff>=0.6",
  "pyright>=1.1.380",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]

[tool.pyright]
venvPath = "."
venv = ".venv"
"""


def _makefile(ctx: _TemplateContext) -> str:
    safety_target = ""
    if "decimal-purity" in {guard.lower() for guard in ctx.spec.safety_guards}:
        safety_target = "\n\tuv run python scripts/prep.py --decimal-purity\n"
    return f""".PHONY: lint test quality

lint:
\tuv run ruff check src tests scripts
\tuv run pyright src tests scripts

test:
\tuv run pytest --cov=src --cov-fail-under={ctx.spec.coverage_floor}

quality: lint test{safety_target}
"""


def _quality_workflow(ctx: _TemplateContext) -> str:
    return f"""name: Quality

on:
  pull_request:
  push:
    branches: [{ctx.spec.main_branch}, {ctx.spec.staging_branch}]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: uv sync --all-extras
      - run: uv run ruff check --fix --unsafe-fixes src tests scripts
      - run: make quality
"""


def _readme(ctx: _TemplateContext) -> str:
    return f"""# {ctx.project_title}

{ctx.spec.description}

## Architecture

| Layer | Path |
|---|---|
| Application package | `src/{ctx.package_name}` |
| Tests | `tests/` |
| ADRs | `docs/adr/` |

## Safety

{ctx.safety_block}
"""


def _claude_md(ctx: _TemplateContext) -> str:
    return f"""# {ctx.project_title}

## Quick Rules

{ctx.safety_block}

## Commands

- `make quality`
- `make test`
"""


def _cli(ctx: _TemplateContext) -> str:
    return f'''"""CLI entrypoint for {ctx.spec.name}."""


def main() -> None:
    """Run the placeholder V1 command."""
    print("{ctx.spec.name} ready")
'''


def _smoke_test(ctx: _TemplateContext) -> str:
    return f"""from {ctx.package_name}.cli import main


def test_main_smoke(capsys):
    main()

    assert "{ctx.spec.name} ready" in capsys.readouterr().out
"""


def _issue_template(ctx: _TemplateContext, name: str) -> str:
    return f"""---
name: {name}
about: HydraFlow-managed {name.lower()}
labels: {ctx.spec.label_prefix}-find
---

## Context

## Expected outcome
"""


def _pull_request_template(ctx: _TemplateContext) -> str:
    return f"""## Summary

## Verification

- [ ] `make quality`

## Domain safety

{ctx.safety_block}
"""


def _adr(ctx: _TemplateContext) -> str:
    return f"""# ADR-0001: Initial Architecture

## Status

Accepted

## Context

{ctx.spec.description}

## Decision

Start with a small Python package, strict quality gate, and HydraFlow-compatible labels.
"""


def _wiki(ctx: _TemplateContext) -> str:
    return f"""# {ctx.project_title} Wiki

This repo was generated from the HydraFlow onboarding invariant kernel.
"""


def _prep_script(ctx: _TemplateContext) -> str:
    return f'''"""Preparation checks for {ctx.spec.name}."""

from __future__ import annotations

import argparse


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--decimal-purity", action="store_true")
    parser.parse_args()


if __name__ == "__main__":
    main()
'''


def _branch_protection_script() -> str:
    return '''"""Apply branch protection for the generated repository.

The onboarding provisioning service calls this script after repository creation.
"""

from __future__ import annotations


def main() -> None:
    raise SystemExit("branch protection is applied by HydraFlow provisioning")


if __name__ == "__main__":
    main()
'''


def _spec_doc(ctx: _TemplateContext) -> str:
    return f"""# {ctx.project_title} Bootstrap Spec

## Name

{ctx.spec.name}

## Description

{ctx.spec.description}

## Architecture Overview

Small Python package with a strict quality gate and HydraFlow-compatible project hygiene.

## V1 IN

- Package skeleton
- Quality workflow
- ADR and wiki seed

## V1 OUT

- Deep domain model
- Production deployment automation
"""


def _plan_doc(ctx: _TemplateContext) -> str:
    return f"""# Plan 01: Bootstrap {ctx.project_title}

1. Materialize invariant kernel.
2. Install dependencies.
3. Run `make quality`.
4. Review wizard-drafted spec and ADR.
5. Push through HydraFlow provisioning.
"""
