#!/usr/bin/env python3
"""Emit this factory's vitals as one JSON document on stdout.

HydraFlow's vitals live in per-repo files — ``disturbance/baselines/*.yaml``,
regenerated by the erosion loops. That is fine for one machine and useless for
several: N factories produce N disconnected artifact sets and no aggregate
view. This is the seam that makes them aggregatable — a single self-describing
document a data plane can ingest and query across hosts.

**Identity is the load-bearing part, not the numbers.** An emitted metric is
worthless in aggregate unless the document says which factory, which commit and
when. Two hosts reporting ``parametrize_copies: 451`` are the same fact or two
different facts depending entirely on whether they are the same repo at the
same SHA, and no consumer can recover that afterwards.

**Metrics are DISCOVERED, not listed.** The baseline set is read from whatever
files exist rather than from a hardcoded roster, because a hardcoded roster
stops seeing a newly-added baseline and reports a smaller, healthy-looking
document with nothing red — the failure class swept in #11673. Adding a
baseline file is sufficient to have it emitted.

This is a VITALS emitter, deliberately. It carries no conformance claim: nothing
here asserts that a gate holds, only what the counters read. Conformance stays
in-repo and offline (see the vitals/conformance seam, #11688) — a claim that
can only be audited through a data plane's uptime is not a claim.

Usage::

    python scripts/emit_vitals.py                 # JSON to stdout
    python scripts/emit_vitals.py --pretty        # indented
"""

from __future__ import annotations

import argparse
import json
import socket
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

_REPO_ROOT = Path(__file__).resolve().parents[1]
_BASELINES = _REPO_ROOT / "disturbance" / "baselines"

#: Baseline keys that are prose, not measurements.
_NON_METRIC_KEYS = frozenset({"comment"})

SCHEMA_VERSION = 1
"""Bumped only when a consumer would have to change. Additive fields do not."""


def _git(*args: str) -> str:
    try:
        out = subprocess.run(
            ["git", *args], cwd=_REPO_ROOT, capture_output=True, text=True, check=False
        )
    except OSError:  # pragma: no cover - git absent
        return ""
    return out.stdout.strip() if out.returncode == 0 else ""


def repo_identity() -> dict[str, Any]:
    """Who is reporting, and about which exact tree.

    ``dirty`` matters more than it looks: a vitals reading taken from a tree
    with uncommitted changes is not a reading of ``head_sha``, and an aggregate
    that mixes the two is comparing a commit against somebody's working copy.
    Reported rather than suppressed, so a consumer can decide.
    """
    remote = _git("remote", "get-url", "origin")
    slug = ""
    if remote:
        slug = remote.removesuffix(".git").removeprefix("git@github.com:")
        slug = slug.removeprefix("https://github.com/")
    return {
        "repo": slug,
        "branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
        "head_sha": _git("rev-parse", "HEAD"),
        "dirty": bool(_git("status", "--porcelain")),
        "host": socket.gethostname(),
    }


def _numbers_in(value: Any) -> list[float]:
    """Every non-bool number reachable in *value*.

    ``isinstance(True, int)`` is True in Python, so a flag would otherwise
    count as a measurement.
    """
    if isinstance(value, bool):
        return []
    if isinstance(value, (int, float)):
        return [float(value)]
    if isinstance(value, dict):
        return [n for v in value.values() for n in _numbers_in(v)]
    if isinstance(value, list):
        return [n for v in value for n in _numbers_in(v)]
    return []


def _field_numbers(collection: Any) -> dict[str, list[float]]:
    """Numeric fields across a collection's members, keyed by field name.

    ``{"a": {"loc": 1}, "b": {"loc": 2}}`` -> ``{"loc": [1.0, 2.0]}``.
    A collection of bare numbers keys them under ``""`` — the value IS the
    field, which is the shape ``suppressions`` and ``traceability`` use.
    """
    members = (
        list(collection.values()) if isinstance(collection, dict) else list(collection)
    )
    fields: dict[str, list[float]] = {}
    for member in members:
        if isinstance(member, dict):
            for key, inner in member.items():
                if key in _NON_METRIC_KEYS:
                    continue
                nums = _numbers_in(inner)
                if nums:
                    fields.setdefault(key, []).extend(nums)
        else:
            nums = _numbers_in(member)
            if nums:
                fields.setdefault("", []).extend(nums)
    return fields


def _summarize(loaded: Any) -> dict[str, float]:
    """One baseline file reduced to a handful of comparable numbers.

    Summarised by SHAPE, never by field name, so a baseline added tomorrow is
    summarised without editing this file. A top-level scalar passes through
    under its own name; a collection yields ``count`` plus ``total``/``max``
    per numeric field found among its members.

    Deliberately lossy. Emitting every leaf produced ~700 keys from
    ``suppressions`` alone — a document that large is not comparable across
    hosts, and the per-entry detail already lives in the repo, which is where
    a conformance question would go looking for it anyway.
    """
    out: dict[str, float] = {}
    if not isinstance(loaded, dict):
        return out
    for key, value in loaded.items():
        if key in _NON_METRIC_KEYS:
            continue
        if isinstance(value, bool):
            continue
        if isinstance(value, (int, float)):
            out[str(key)] = float(value)
            continue
        if isinstance(value, (dict, list)):
            out[f"{key}.count"] = float(len(value))
            for field, nums in _field_numbers(value).items():
                stem = f"{key}.{field}" if field else str(key)
                out[f"{stem}.total"] = float(sum(nums))
                out[f"{stem}.max"] = float(max(nums))
    return out


def baseline_metrics(baselines_dir: Path = _BASELINES) -> dict[str, dict[str, float]]:
    """Every baseline file's numbers, keyed by file stem.

    Discovery by glob is the point — see the module docstring. A file that
    fails to parse is reported as an explicit error entry rather than skipped,
    because a silently-absent metric reads as a healthy zero.
    """
    out: dict[str, dict[str, float]] = {}
    for path in sorted(baselines_dir.glob("*.yaml")):
        try:
            loaded = yaml.safe_load(path.read_text()) or {}
        except yaml.YAMLError as exc:
            out[path.stem] = {"_unparseable": 1.0}
            print(f"warning: {path.name}: {exc}", file=sys.stderr)
            continue
        out[path.stem] = _summarize(loaded)
    return out


def emit(*, now: datetime | None = None) -> dict[str, Any]:
    """The whole document."""
    stamped = now or datetime.now(UTC)
    return {
        "schema_version": SCHEMA_VERSION,
        "kind": "hydraflow.vitals",
        "emitted_at": stamped.isoformat(),
        "identity": repo_identity(),
        "baselines": baseline_metrics(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pretty", action="store_true", help="indent the JSON")
    args = parser.parse_args(argv)
    doc = emit()
    json.dump(doc, sys.stdout, indent=2 if args.pretty else None, sort_keys=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
