"""Render the escape ledger to Markdown (#10367).

Follows ``loop-fitness.md``'s generated-report convention: a runtime-written
``docs/arch/generated/escape-ledger.md`` (gitignored — the loop rewrites it
each tick), NOT an ``arch-regen`` artifact. Pure over ``list[EscapeRecord]``
+ an injected merge count / ``now`` so the rendered numbers match the metrics
module exactly and the render is unit-testable.

The "Recent escapes" table's ``evidence`` column surfaces
``EscapeRecord.notes`` (#11185) — the only place the concrete encoding
(regression-test path, ADR number, or stored lesson) is recorded, so an
operator can point at the encoding without grepping the JSONL.
"""

from __future__ import annotations

from datetime import datetime

from escape import metrics
from escape.models import EscapeRecord
from escape.notes import sanitize_notes_cell


def _fmt_hours(value: float | None) -> str:
    return "—" if value is None else f"{value:.1f}h"


def _fmt_num(value: float | None) -> str:
    return "—" if value is None else f"{value:.1f}"


def render_escape_ledger_markdown(
    records: list[EscapeRecord],
    *,
    now: datetime,
    merge_count_30d: int,
) -> str:
    """Render the full escape-ledger report as Markdown."""
    rolling = metrics.rolling_escape_count(records, now, days=30)
    rate = metrics.escapes_per_100_merges(rolling, merge_count_30d)
    confirmed_rolling = metrics.rolling_confirmed_escape_count(records, now, days=30)
    confirmed_rate = metrics.escapes_per_100_merges(confirmed_rolling, merge_count_30d)
    ttd = metrics.time_to_detection_stats(records)
    encoded = metrics.encoded_summary(records)
    months = metrics.monthly_series(records)

    lines: list[str] = []
    lines.append("# Escape ledger")
    lines.append("")
    lines.append(
        "> Generated by `EscapeLedgerLoop` (#10367) — the falsification "
        "instrument for gate escapes. Read-only (ADR-0029 Pattern B): it "
        "records defects discovered AFTER merge and never gates or fixes."
    )
    lines.append("")
    lines.append(f"_Generated at {now.isoformat()}_")
    lines.append("")

    lines.append("## Headline")
    lines.append("")
    lines.append(
        "> **Confirmed** = high/medium mechanical-attribution confidence. The "
        "confirmed rate excludes low-confidence `bug-issue` (`fix: … fixes #N`) "
        "closes, which in a fix-heavy repo would otherwise conflate ordinary "
        "issue resolution with real gate escapes."
    )
    lines.append("")
    lines.append("| metric | value |")
    lines.append("|---|---|")
    lines.append(f"| escapes (rolling 30d, all confidence) | {rolling} |")
    lines.append(f"| confirmed escapes (rolling 30d) | {confirmed_rolling} |")
    lines.append(f"| merged changes (rolling 30d) | {merge_count_30d} |")
    lines.append(f"| **confirmed escapes per 100 merges** | **{confirmed_rate:.2f}** |")
    lines.append(f"| escapes per 100 merges (all confidence) | {rate:.2f} |")
    lines.append(f"| total recorded escapes | {encoded.total} |")
    lines.append(f"| encoded / unencoded | {encoded.encoded} / {encoded.unencoded} |")
    lines.append("")

    lines.append("## Time to detection")
    lines.append("")
    lines.append("| detection source | n | median | p90 |")
    lines.append("|---|---|---|---|")
    for source in sorted(ttd):
        stat = ttd[source]
        lines.append(
            f"| {source} | {stat.n} | {_fmt_hours(stat.median_hours)} | "
            f"{_fmt_hours(stat.p90_hours)} |"
        )
    lines.append("")

    lines.append("## Encoding closure")
    lines.append("")
    lines.append("| encoded_as | count |")
    lines.append("|---|---|")
    for status in sorted(encoded.by_status):
        lines.append(f"| {status} | {encoded.by_status[status]} |")
    if not encoded.by_status:
        lines.append("| (none yet) | 0 |")
    lines.append("")

    lines.append("## Monthly series")
    lines.append("")
    lines.append("| month | escapes | by source |")
    lines.append("|---|---|---|")
    for row in months:
        by_source = ", ".join(f"{src}={n}" for src, n in sorted(row.by_source.items()))
        lines.append(f"| {row.month} | {row.total} | {by_source or '—'} |")
    if not months:
        lines.append("| (no escapes recorded) | 0 | — |")
    lines.append("")

    lines.append("## Recent escapes")
    lines.append("")
    lines.append(
        "| detected_at | source | ref | originating merge | ttd | "
        "attribution | confidence | encoded_as | evidence |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|")
    recent = sorted(records, key=lambda r: r.detected_at, reverse=True)[:25]
    for r in recent:
        merge = r.originating_merge_sha[:7] if r.originating_merge_sha else "—"
        lines.append(
            f"| {r.detected_at} | {r.detection_source} | "
            f"`{r.detection_ref[:12]}` | {merge} | "
            f"{_fmt_num(r.time_to_detection_hours)} | {r.attribution_method} | "
            f"{r.attribution_confidence} | {r.encoded_as} | "
            f"{sanitize_notes_cell(r.notes)} |"
        )
    if not recent:
        lines.append("| (no escapes recorded) | — | — | — | — | — | — | — | — |")
    lines.append("")

    return "\n".join(lines) + "\n"
