"""Backlog-budget retirement valve (#11298) — pure selection engine.

The board-churn root cause, half two: filing has budgets and dedup
(#10840 counter-metrics, #11341 cross-tick folding) but retirement had
none — advisory factory-generated issues accumulated until a human
bulk-cleared them (88 open on 2026-08-16). This engine picks which
advisory issues to retire when the board exceeds ``config.backlog_budget``.

Selection contract (conservative by construction):

- Only issues carrying an ADVISORY stage label (find/plan/diagnose/parked)
  are candidates — the classes the factory files for itself.
- PROTECTED issues are never candidates: anything in-progress, ready,
  review, HITL-active, human-required, epics and epic children, or
  carrying an operator-priority label (P1/P2).
- A grace period exempts fresh filings (``backlog_budget_min_age_days``).
- Retirement is oldest-first and only down to the budget, capped per
  cycle by the caller — the valve bleeds pressure, it never drains the
  board.

Retirement is cheap and reversible by design: the class key survives
(#11341), so a pattern that recurs or bites operationally refiles into
the same identity.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Any

#: Labels marking an issue the factory filed for itself and nobody started.
ADVISORY_STAGE_LABELS: frozenset[str] = frozenset(
    {
        "hydraflow-find",
        "hydraflow-plan",
        "hydraflow-diagnose",
        "hydraflow-parked",
    }
)

#: Labels that make an issue untouchable regardless of age or budget.
PROTECTED_LABELS: frozenset[str] = frozenset(
    {
        "hydraflow-ready",
        "hydraflow-review",
        "hydraflow-in-progress",
        "hydraflow-hitl",
        "hydraflow-hitl-active",
        "hydraflow-hitl-autofix",
        "hydraflow-auto-light",
        "human-required",
        "hydraflow-epic",
        "hydraflow-epic-child",
        "hydraflow-refinement-digest",
        "P1",
        "P2",
    }
)

RETIREMENT_COMMENT = (
    "## Retired by the backlog-budget valve (#11298)\n\n"
    "The advisory backlog exceeded `backlog_budget`; this was among the "
    "oldest unstarted advisory filings, so it is retired to keep the board "
    "equal to active work. **This is not a verdict on the finding.** The "
    "class key is retained (#11341 cross-tick folding) — if the pattern "
    "recurs or bites operationally, the finder refiles it into the same "
    "identity.\n\n---\n*Generated by HydraFlow StaleIssueLoop*"
)


@dataclass(frozen=True)
class RetirementPick:
    number: int
    title: str
    age_days: float


def _labels_of(issue: dict[str, Any]) -> set[str]:
    raw = issue.get("labels") or []
    out: set[str] = set()
    for label in raw:
        if isinstance(label, dict):
            name = label.get("name")
            if name:
                out.add(str(name))
        elif isinstance(label, str):
            out.add(label)
    return out


def _created_at(issue: dict[str, Any]) -> datetime | None:
    raw = issue.get("created_at") or issue.get("createdAt")
    if not raw:
        return None
    try:
        return datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except ValueError:
        return None


def retirement_picks(
    open_issues: list[dict[str, Any]],
    *,
    budget: int,
    min_age_days: int,
    now: datetime,
    max_per_cycle: int = 10,
    advisory_labels: frozenset[str] | None = None,
    protected_labels: frozenset[str] | None = None,
) -> list[RetirementPick]:
    """Oldest advisory issues beyond *budget*, capped at *max_per_cycle*.

    ``budget <= 0`` disables the valve (returns ``[]``). The budget is
    measured against the ADVISORY population only — protected issues
    neither count toward the budget nor are ever picked.
    """
    if budget <= 0:
        return []
    # ``is not None`` (not truthiness): an explicitly-empty advisory set
    # means "retire nothing", and a truthy check would silently substitute
    # the module default — retiring issues the caller excluded (#11408).
    advisory_set = (
        advisory_labels if advisory_labels is not None else ADVISORY_STAGE_LABELS
    )
    protected_set = (
        protected_labels if protected_labels is not None else PROTECTED_LABELS
    )
    advisory: list[tuple[datetime, dict[str, Any]]] = []
    for issue in open_issues:
        labels = _labels_of(issue)
        if not labels & advisory_set:
            continue
        if labels & protected_set:
            continue
        created = _created_at(issue)
        if created is None:
            continue
        advisory.append((created, issue))
    overage = len(advisory) - budget
    if overage <= 0:
        return []
    grace = timedelta(days=min_age_days)
    picks: list[RetirementPick] = []
    for created, issue in sorted(advisory, key=lambda pair: pair[0]):
        if len(picks) >= min(overage, max_per_cycle):
            break
        if now - created < grace:
            continue
        number = int(issue.get("number", 0))
        if number <= 0:
            continue
        picks.append(
            RetirementPick(
                number=number,
                title=str(issue.get("title", "")),
                age_days=(now - created).total_seconds() / 86400,
            )
        )
    return picks
