"""DetectorCalibrationLoop — repeat-escalation churn miner.

The over-eager-auditor meta-pattern recurred twice (the ADR-drift and
fake-coverage FP campaigns) and each time ran for WEEKS before a human
noticed that the same subject kept escalating — the detector was
miscalibrated, not the code. This caretaker watches the factory's own
sensors: it mines closed ``hitl-escalation`` issues, normalizes titles
(``#N`` digit runs are entity identity — an issue/PR reference — and are
kept verbatim; other bare digit runs are volatile, e.g. attempt counts and
elapsed seconds, and collapse to ``#`` so they don't split one subject
into many — see #11405), and files one ``hydraflow-find`` +
``detector-calibration`` issue per subject that escalated at least
``_REPEAT_THRESHOLD`` times inside ``_WINDOW_DAYS``.

A second, separately-keyed class catches the breadth shape #11405's
identity-preserving normalize can no longer collapse on its own: one
escalation *template* fired against many distinct ``#N`` entities. See
:func:`template_key` and #11427.

Recursion is bounded at one meta-layer (ADR-0045 §12.1): this loop files
find issues only — it never escalates, and nothing meta-watches it beyond
the ordinary loop supervision.

The issue body embeds a ``Norm-Key:`` (subject class) or ``Template-Key:``
(spray class) line so recovery can reverse-map an open calibration issue
to its subject/template: when the churn or spray stops (the window rolls
past the repeats/entities), the issue auto-closes and the dedup key
clears, re-arming detection for a genuine recurrence.

Generated by scripts/scaffold_loop.py; body implemented per the
dark-factory hardening roadmap (Fix F); spray class added per #11427.
"""

from __future__ import annotations

import hashlib
import logging
import re
from datetime import UTC, datetime, timedelta
from typing import Any

from base_background_loop import BaseBackgroundLoop, LoopDeps
from config import HydraFlowConfig
from dedup_store import DedupStore
from filing_budget import FilingBudget, file_overflow_summary, overflow_line
from loop_fitness import Confidence, FitnessContext, FitnessKind, LoopFitness

logger = logging.getLogger("hydraflow.detector_calibration")

# Two closed escalations of the same normalized subject inside the window
# = the close→re-fire cycle completed twice = churn. Deliberately low: the
# whole point is catching miscalibration in days, not weeks.
_REPEAT_THRESHOLD = 2
_WINDOW_DAYS = 30
# Closed-scan page size. At ~7 escalation closes/day a 30-day window holds
# ~210 issues; 500 gives margin. A scan that comes back AT this cap is
# treated as potentially truncated: filing still proceeds (repeats found in
# a partial scan are real) but auto-close is skipped — closing on a scan
# that may have hidden the churning subject would make the miner itself
# churn (file → premature close → dedup re-arm → refile).
_SCAN_LIMIT = 500
_ISSUE_LABELS = ("hydraflow-find", "detector-calibration")
_NORM_KEY_PREFIX = "Norm-Key:"
_TEMPLATE_KEY_PREFIX = "Template-Key:"

_NUM_RE = re.compile(r"#\d+|\d+")
_ENTITY_REF_RE = re.compile(r"#\d+")
_TEMPLATE_PLACEHOLDER = "#n"
_TEMPLATE_MIN_ALPHA_TOKENS = 3


def _normalize(title: str) -> str:
    """Collapse volatile numerics so retries of one subject share a key.

    A ``#``-prefixed digit run is entity identity (an issue/PR reference)
    and is preserved verbatim — collapsing it would fold distinct PRs into
    one fabricated "churn" subject (#11405). Any other digit run (attempt
    counts, elapsed seconds) is volatile and collapses to ``#``.
    """

    def _collapse(match: re.Match[str]) -> str:
        text = match.group(0)
        return text if text.startswith("#") else "#"

    return _NUM_RE.sub(_collapse, title.strip().lower())


def template_key(norm: str) -> str | None:
    """Derive a spray-detection key from an already-normalized title.

    Replaces each surviving ``#N`` entity reference with a placeholder so
    one escalation *template* fired against many distinct entities
    collapses to a single key — the compensating breadth signal #11405's
    identity-preserving :func:`_normalize` traded away when it started
    keeping ``#N`` as entity identity (see #11427).

    Returns ``None`` (reject) for degenerate templates that would
    over-match:

    - No ``#N`` reference survives at all — nothing was stripped, so this
      title carries no per-entity identity to generalize over.
    - Fewer than :data:`_TEMPLATE_MIN_ALPHA_TOKENS` real alphabetic tokens
      remain after stripping — too generic a phrase to be a meaningful
      template; a bare phrase like ``"escalation #n"`` would otherwise
      flag unrelated escalations as one spray. Counted on *norm* (before
      the placeholder substitution) so the placeholder's own letters
      don't pad the count.
    """
    templated, count = _ENTITY_REF_RE.subn(_TEMPLATE_PLACEHOLDER, norm)
    if count == 0:
        return None
    if len(re.findall(r"[a-z]+", norm)) < _TEMPLATE_MIN_ALPHA_TOKENS:
        return None
    return templated


def _parse_ts(value: str) -> datetime | None:
    try:
        ts = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return None
    return ts if ts.tzinfo else ts.replace(tzinfo=UTC)


class DetectorCalibrationLoop(BaseBackgroundLoop):
    """Files a calibration finding when one subject escalates repeatedly."""

    def __init__(
        self,
        *,
        config: HydraFlowConfig,
        state: Any,
        pr_manager: Any,  # PRPort
        deps: LoopDeps,
        github_cache: Any,  # GitHubDataCache
    ) -> None:
        super().__init__(
            worker_name="detector_calibration",
            config=config,
            deps=deps,
            run_on_startup=False,
        )
        self._state = state
        self._pr = pr_manager
        self._github_cache = github_cache
        self._dedup = DedupStore(
            "detector_calibration",
            config.data_root / "dedup" / "detector_calibration.json",
        )

    def _get_default_interval(self) -> int:
        return self._config.detector_calibration_interval

    def loop_fitness(self, ctx: FitnessContext) -> LoopFitness:
        """HOUSEKEEPING fitness (no normalized objective yet).

        Required override — new loops are NOT grandfathered by
        tests/test_loop_fitness_completeness.py. Must stay PURE over
        ``ctx`` — no network, no clock, no mutable ``self`` state.
        """
        return LoopFitness(
            worker_name=self._worker_name,
            kind=FitnessKind.HOUSEKEEPING,
            components={},
            sample_count=0,
            confidence=Confidence.INSUFFICIENT_DATA,
            timestamp=ctx.window_end,
        )

    async def _do_work(self) -> dict[str, Any] | None:
        # ADR-0049 in-body kill-switch (universal mandate).
        if not self._enabled_cb(self._worker_name):
            return {"status": "disabled"}

        # Static config gate (defense-in-depth: deploy-time disable).
        if not self._config.detector_calibration_enabled:
            return {"status": "config_disabled"}

        # #9814: served from the shared GitHubDataCache snapshot instead of
        # a per-tick `gh issue list`. gh failure degrades to a stale
        # snapshot (then []) inside the cache — a [] scan simply files
        # nothing and skips auto-close (scan_was_capped stays False but
        # churning is empty), never crashes the loop.
        closed = await self._github_cache.get_issues_by_label(
            "hitl-escalation", state="closed", limit=_SCAN_LIMIT
        )
        cutoff = datetime.now(UTC) - timedelta(days=_WINDOW_DAYS)
        repeats: dict[str, list[int]] = {}
        # tkey -> entity ref (e.g. "#11405") -> escalation issue numbers
        # that reference it under this template.
        spray_groups: dict[str, dict[str, list[int]]] = {}
        for issue in closed:
            # Window keys on closed_at (#9727): updated_at moves on ANY
            # activity — a comment on an old closed escalation would pull
            # it back into the window and fabricate a repeat.
            # Fall back to updated_at only when closed_at is absent entirely
            # (pre-#9727 rows) — the fabricated-repeat FP mode returns only
            # for those legacy rows, and findings stay advisory/auto-close.
            ts = _parse_ts(str(issue.get("closed_at", ""))) or _parse_ts(
                str(issue.get("updated_at", ""))
            )
            number = issue.get("number")
            if ts is None or ts < cutoff or not number:
                continue
            key = _normalize(str(issue.get("title", "")))
            if not key:
                continue
            repeats.setdefault(key, []).append(int(number))
            tkey = template_key(key)
            if tkey is None:
                continue
            entities = spray_groups.setdefault(tkey, {})
            for entity in set(_ENTITY_REF_RE.findall(key)):
                entities.setdefault(entity, []).append(int(number))
        churning = {
            key: sorted(nums)
            for key, nums in repeats.items()
            if len(nums) >= _REPEAT_THRESHOLD
        }
        # #11427: distinct entities, not occurrences — one entity escalating
        # repeatedly stays subject-class only (see `churning` above); this
        # class exists to catch the opposite shape, many distinct entities
        # under one template.
        spraying = {
            tkey: entities
            for tkey, entities in spray_groups.items()
            if len(entities) >= self._config.detector_calibration_spray_min_entities
        }

        filed = await self._file_findings(churning, spraying)
        # An EMPTY scan is as unreliable as a capped one (#9814): the cache
        # degrades to [] when gh is down past the stale-serve grace, and
        # auto-closing every open finding because the scan saw nothing
        # would be the spurious-close failure mode. Findings only exist
        # because closed escalations churned recently, so a genuine scan
        # virtually always carries rows (the 500-row scan is not
        # date-filtered; old closed rows remain visible).
        autoclosed = await self._autoclose_recovered(
            churning,
            spraying,
            scan_was_capped=len(closed) >= _SCAN_LIMIT or not closed,
        )

        status = "fired" if filed or autoclosed else "noop"
        return {
            "status": status,
            "filed": filed,
            "autoclosed": autoclosed,
            "churning_subjects": len(churning),
            "spraying_templates": len(spraying),
            "closed_scanned": len(closed),
        }

    async def _file_findings(
        self,
        churning: dict[str, list[int]],
        spraying: dict[str, dict[str, list[int]]],
    ) -> int:
        # Per-tick filing cap (#10777): findings are mined from up to 500
        # closed escalations, so a fleet-wide churn/spray spike could file
        # one issue per subject/template. Both classes share ONE budget
        # (#11427) so the combined per-tick output stays bounded; over the
        # cap, findings are recorded (so they are not re-filed individually)
        # and folded into ONE summary issue.
        budget = FilingBudget(cap=self._config.detector_calibration_max_issues_per_tick)
        keys = self._dedup.get()

        # Spray files first (#11427): a template spraying many distinct
        # entities is the compensating breadth signal #11405's
        # identity-preserving _normalize can no longer catch via
        # cross-entity collapse.
        for tkey, entities in spraying.items():
            dedup_key = f"detector_calibration_spray:{_digest(tkey)}"
            if dedup_key in keys:
                continue
            if not budget.allow():
                keys = keys | {dedup_key}
                self._dedup.set_all(keys)
                budget.note_overflow(
                    overflow_line(
                        tkey[:100], f"{len(entities)} entities/{_WINDOW_DAYS}d"
                    )
                )
                continue
            refs = ", ".join(sorted(entities))
            title = (
                f"Detector calibration: escalation spray — "
                f"{tkey[:100]} ({len(entities)} entities/{_WINDOW_DAYS}d)"
            )
            body = (
                f"The same escalation template fired against "
                f"{len(entities)} distinct entities in the last "
                f"{_WINDOW_DAYS} days ({refs}). Per the over-eager-auditor "
                f"meta-pattern, one template spraying many distinct "
                f"subjects means the DETECTOR is miscalibrated — it is "
                f"over-citing, not each individual subject it names.\n\n"
                f"Repair path: right-size the detector — narrow its "
                f"registry/citation scope or raise its evidence bar — "
                f"rather than re-fixing each cited subject. See #11427.\n\n"
                f"{_TEMPLATE_KEY_PREFIX} `{tkey}`\n\n"
                f"_Auto-filed by `detector_calibration` "
                f"(meta-observability, one-layer bound per ADR-0045 "
                f"§12.1). Auto-closes when the spray window clears._"
            )
            await self._pr.create_issue(title, body, list(_ISSUE_LABELS))
            keys = keys | {dedup_key}
            self._dedup.set_all(keys)
            budget.note_filed()

        for norm, numbers in churning.items():
            tkey = template_key(norm)
            if tkey is not None and tkey in spraying:
                # Folded into the spray finding above — same underlying
                # miscalibration. Skip filing WITHOUT touching dedup
                # (#11427): recording this subject's key here would
                # permanently suppress it even after the spray stops.
                continue
            dedup_key = f"detector_calibration:{_digest(norm)}"
            if dedup_key in keys:
                continue
            if not budget.allow():
                keys = keys | {dedup_key}
                self._dedup.set_all(keys)
                budget.note_overflow(
                    overflow_line(norm[:100], f"{len(numbers)}x/{_WINDOW_DAYS}d")
                )
                continue
            refs = ", ".join(f"#{n}" for n in numbers)
            title = (
                f"Detector calibration: escalation churn — "
                f"{norm[:100]} ({len(numbers)}x/{_WINDOW_DAYS}d)"
            )
            body = (
                f"The same escalation subject closed and re-fired "
                f"{len(numbers)} times in the last {_WINDOW_DAYS} days "
                f"({refs}). Per the over-eager-auditor meta-pattern "
                f"(ADR-drift + fake-coverage FP campaigns), repeated churn "
                f"on one subject means the DETECTOR is miscalibrated, not "
                f"the code.\n\n"
                f"Repair path: right-size the detector — narrow its "
                f"registry/citation scope, fix its title/subject parsing, "
                f"or raise its evidence bar — rather than re-fixing the "
                f"subject. See the fake-coverage right-sizing notes "
                f"(#9403) and the ADR-drift right-sizing notes (#9405).\n\n"
                f"{_NORM_KEY_PREFIX} `{norm}`\n\n"
                f"_Auto-filed by `detector_calibration` "
                f"(meta-observability, one-layer bound per ADR-0045 "
                f"§12.1). Auto-closes when the churn window clears._"
            )
            await self._pr.create_issue(title, body, list(_ISSUE_LABELS))
            keys = keys | {dedup_key}
            self._dedup.set_all(keys)
            budget.note_filed()
        summary_filed = await file_overflow_summary(
            create_issue=self._pr.create_issue,
            dedup=self._dedup,
            budget=budget,
            key_prefix="detector_calibration",
            labels=_ISSUE_LABELS,
            title="Detector calibration: churning subjects over per-tick filing cap",
            intro=(
                "**Automated — DetectorCalibrationLoop per-tick filing cap (#10777).**"
            ),
        )
        return budget.filed + summary_filed

    async def _autoclose_recovered(
        self,
        churning: dict[str, list[int]],
        spraying: dict[str, dict[str, list[int]]],
        *,
        scan_was_capped: bool = False,
    ) -> int:
        """Close open calibration issues whose subject/template stopped churning.

        Skipped entirely when the closed-issues scan hit ``_SCAN_LIMIT`` —
        a truncated scan can hide a still-churning subject or spraying
        template, and a premature close re-arms dedup into refile churn.
        """
        if scan_was_capped:
            return 0
        keys = self._dedup.get()
        if not keys:
            return 0
        # #9814: cached read — same degrade discipline as the closed scan.
        open_findings = await self._github_cache.get_issues_by_label(
            "detector-calibration"
        )
        autoclosed = 0
        for issue in open_findings:
            body = str(issue.get("body", ""))
            number = issue.get("number")
            if not number:
                continue
            # #11427: check Template-Key: before Norm-Key: — a spray
            # finding's body carries only the former, but testing subject
            # membership first on a misclassified read would auto-close a
            # still-spraying finding the moment the tick after filing rolls.
            tkey = _extract_template_key(body)
            if tkey is not None:
                if tkey in spraying:
                    continue
                dedup_key = f"detector_calibration_spray:{_digest(tkey)}"
                comment = (
                    "The escalation spray window has cleared for this "
                    "template — auto-closing. Detection re-arms; a genuine "
                    "recurrence files fresh."
                )
            else:
                norm = _extract_norm_key(body)
                if norm is None or norm in churning:
                    continue
                dedup_key = f"detector_calibration:{_digest(norm)}"
                comment = (
                    "The escalation churn window has cleared for this "
                    "subject — auto-closing. Detection re-arms; a genuine "
                    "recurrence files fresh."
                )
            await self._pr.post_comment(number, comment)
            await self._pr.close_issue(number)
            keys = keys - {dedup_key}
            self._dedup.set_all(keys)
            autoclosed += 1
        return autoclosed


def _digest(norm: str) -> str:
    return hashlib.sha256(norm.encode()).hexdigest()[:12]


def _extract_norm_key(body: str) -> str | None:
    for line in body.splitlines():
        if line.startswith(_NORM_KEY_PREFIX):
            return line[len(_NORM_KEY_PREFIX) :].strip().strip("`")
    return None


def _extract_template_key(body: str) -> str | None:
    for line in body.splitlines():
        if line.startswith(_TEMPLATE_KEY_PREFIX):
            return line[len(_TEMPLATE_KEY_PREFIX) :].strip().strip("`")
    return None
