"""Background worker loop — diagnostic self-healing for escalated issues."""

from __future__ import annotations

import hashlib
import logging
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

from base_background_loop import BaseBackgroundLoop, LoopDeps
from config import HydraFlowConfig
from dedup_store import DedupStore
from events import EventType, HydraFlowEvent
from exception_classify import reraise_on_credit_or_bug
from models import AttemptRecord, Severity

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

    from diagnostic_runner import DiagnosisResult, DiagnosticRunner
    from models import EscalationContext
    from ports import PRPort
    from state import StateTracker
    from workspace import WorkspaceManager

logger = logging.getLogger("hydraflow.diagnostic_loop")


def _format_severity(severity: Severity) -> str:
    """Return a human-readable severity label."""
    labels = {
        Severity.P0_SECURITY: "P0 — Security",
        Severity.P1_BLOCKING: "P1 — Pipeline Blocking",
        Severity.P2_FUNCTIONAL: "P2 — Functional Bug",
        Severity.P3_WIRING: "P3 — Wiring / Config",
        Severity.P4_HOUSEKEEPING: "P4 — Housekeeping",
    }
    return labels.get(severity, str(severity))


def _format_diagnosis_comment(diagnosis: DiagnosisResult) -> str:
    """Format a diagnosis result as a markdown comment."""
    affected = (
        ", ".join(f"`{f}`" for f in diagnosis.affected_files)
        if diagnosis.affected_files
        else "_unknown_"
    )
    return (
        "## Diagnostic Analysis\n\n"
        f"**Severity:** {_format_severity(diagnosis.severity)}\n"
        f"**Root Cause:** {diagnosis.root_cause}\n"
        f"**Affected Files:** {affected}\n\n"
        "### Fix Plan\n"
        f"{diagnosis.fix_plan or '_No fix plan generated._'}\n\n"
        "### Human Guidance\n"
        f"{diagnosis.human_guidance or '_No guidance available._'}\n\n"
        "---\n"
        "*Generated by HydraFlow Diagnostic Agent*"
    )


class DiagnosticLoop(BaseBackgroundLoop):
    """Polls for ``hydraflow-diagnose`` issues and runs the two-stage diagnostic agent.

    Stage 1 (diagnose): Read-only analysis of root cause and severity.
    Stage 2 (fix): Attempt an automated fix inside the issue's worktree.

    On success the issue is transitioned to ``hydraflow-review``.
    On failure (not fixable, or attempts exhausted) the issue is escalated
    to ``hydraflow-hitl`` with the full diagnosis as a comment.
    """

    # Longer watchdog: each cycle spawns a two-stage (diagnose + fix) LLM
    # subprocess per queued issue, serially (#11262).
    LONG_LLM_CYCLE = True

    def __init__(
        self,
        config: HydraFlowConfig,
        runner: DiagnosticRunner,
        prs: PRPort,
        state: StateTracker,
        deps: LoopDeps,
        workspaces: WorkspaceManager | None = None,  # noqa: UP007
    ) -> None:
        super().__init__(
            worker_name="diagnostic",
            config=config,
            deps=deps,
        )
        self._runner = runner
        self._prs = prs
        self._state = state
        self._workspaces = workspaces
        # #9895 (absorbed #9845): during the 2026-06 exhaustion the loop
        # posted ~33 identical no-op diagnosis comments on one issue. Keyed
        # by issue + content hash, at most one key per issue (replaced when
        # the diagnosis text changes), so re-runs re-post only NEW content.
        self._hitl_comment_dedup = DedupStore(
            "diagnostic_hitl_comments",
            config.data_root / "dedup" / "diagnostic_hitl_comments.json",
        )

    def _get_default_interval(self) -> int:
        return self._config.diagnostic_interval

    async def _do_work(self) -> dict[str, Any] | None:
        """Poll for diagnosed issues and run the diagnostic pipeline."""
        if not self._enabled_cb(self._worker_name):
            return {"status": "disabled"}
        if not self._config.diagnostic_loop_enabled:
            return {"status": "config_disabled"}
        try:
            issues = await self._prs.list_issues_by_label(
                self._config.diagnose_label[0]
            )
        except Exception as exc:
            reraise_on_credit_or_bug(exc)
            logger.warning("Failed to fetch issues for diagnostic check", exc_info=True)
            return {"processed": 0, "fixed": 0, "escalated": 0, "retried": 0}

        processed = 0
        escalated = 0
        fixed = 0
        retried = 0

        for raw_issue in issues:
            if self._stop_event.is_set():
                break
            issue_number = raw_issue.get("number", 0)
            if not issue_number:
                continue
            issue_title = raw_issue.get("title", "")
            issue_body = raw_issue.get("body", "") or ""
            # CH-6 (#10000): thread the issue's labels down to the runner so
            # a data-class:<class> label elevates the prompt gate for the
            # diagnose/fix spawns. Labels ride the gh wire shape
            # ([{"name": ...}]) on the OPEN listing (#9943).
            issue_labels = tuple(
                label["name"]
                for label in raw_issue.get("labels") or []
                if isinstance(label, dict) and label.get("name")
            )
            outcome = await self._process_issue(
                issue_number, issue_title, issue_body, issue_labels
            )
            processed += 1
            if outcome == "fixed":
                fixed += 1
            elif outcome == "retry":
                retried += 1
            else:
                escalated += 1

        return {
            "processed": processed,
            "fixed": fixed,
            "escalated": escalated,
            "retried": retried,
        }

    async def _process_issue(  # noqa: PLR0911
        self,
        issue_number: int,
        issue_title: str,
        issue_body: str,
        issue_labels: Sequence[str] = (),
    ) -> str:
        """Run the full diagnostic pipeline for a single issue.

        Returns ``"fixed"`` when the issue was successfully repaired and
        transitioned to review, ``"retry"`` when the fix failed but attempts
        remain, or ``"escalated"`` when it was sent to HITL.
        """
        # --- Load escalation context ---
        context = self._state.get_escalation_context(issue_number)
        if context is None:
            logger.warning(
                "Diagnostic: no escalation context for issue #%d — escalating to HITL",
                issue_number,
            )
            await self._escalate_missing_context(issue_number)
            return "escalated"

        # --- Load previous attempts (used for context enrichment + limit check) ---
        attempts = self._state.get_diagnostic_attempts(issue_number)
        if attempts:
            context = context.model_copy(update={"previous_attempts": attempts})

        # --- Stage 1: Diagnose ---
        diagnosis = await self._diagnose(
            issue_number, issue_title, issue_body, context, issue_labels
        )
        diagnosis_comment = _format_diagnosis_comment(diagnosis)

        # --- Gates: not-fixable / attempts exhausted both escalate ---
        gated = await self._check_diagnosis_gates(
            issue_number, diagnosis, attempts, diagnosis_comment
        )
        if gated is not None:
            return gated

        # --- Stage 2: Fix ---
        return await self._attempt_fix(
            issue_number,
            issue_title,
            issue_body,
            diagnosis,
            attempts,
            diagnosis_comment,
            issue_labels,
        )

    async def _escalate_missing_context(self, issue_number: int) -> None:
        """Escalate an issue that has no stored escalation context to HITL."""
        await self._escalate_to_hitl(
            issue_number,
            comment=(
                "## Diagnostic Analysis\n\n"
                "**Severity:** P2 — Functional Bug\n"
                "**Root Cause:** No escalation context found in state.\n"
                "**Affected Files:** _unknown_\n\n"
                "### Fix Plan\n"
                "_Cannot diagnose without escalation context._\n\n"
                "### Human Guidance\n"
                "Please review this issue manually — the diagnostic agent "
                "could not locate context for it.\n\n"
                "---\n"
                "*Generated by HydraFlow Diagnostic Agent*"
            ),
        )

    async def _diagnose(
        self,
        issue_number: int,
        issue_title: str,
        issue_body: str,
        context: EscalationContext,
        issue_labels: Sequence[str] = (),
    ) -> DiagnosisResult:
        """Stage 1: run the diagnose agent and persist the severity."""
        logger.info(
            "Diagnostic: running Stage 1 (diagnose) for issue #%d", issue_number
        )
        await self._publish_update(issue_number, "diagnosing")
        diagnosis = await self._runner.diagnose(
            issue_number, issue_title, issue_body, context, issue_labels=issue_labels
        )
        self._state.set_diagnosis_severity(issue_number, diagnosis.severity)
        return diagnosis

    async def _check_diagnosis_gates(
        self,
        issue_number: int,
        diagnosis: DiagnosisResult,
        attempts: list[AttemptRecord],
        diagnosis_comment: str,
    ) -> str | None:
        """Escalate when the diagnosis is not fixable or attempts are exhausted.

        Returns ``"escalated"`` if a gate fired (and HITL escalation happened),
        otherwise ``None`` to signal the fix stage should proceed.
        """
        if diagnosis.infra_failure:
            # #11370: the diagnosis spawn failed for lane/infra reasons
            # (failover-lane structured-output attrition) — the verdict says
            # nothing about the issue. Park for the next cycle instead of
            # escalating; no attempt is recorded, so budget is preserved for
            # runs that actually reached the issue.
            logger.warning(
                "Diagnostic: issue #%d diagnosis failed on infra "
                "(failover-lane parse failure) — parking for retry, "
                "not escalating (#11370)",
                issue_number,
            )
            return "retry"

        if not diagnosis.fixable:
            logger.info(
                "Diagnostic: issue #%d not fixable (severity=%s) — escalating to HITL",
                issue_number,
                diagnosis.severity,
            )
            await self._escalate_to_hitl(issue_number, comment=diagnosis_comment)
            return "escalated"

        if len(attempts) >= self._config.max_diagnostic_attempts:
            # Attempts-exhausted is an auto-resolvable "too-big / wrong-strategy"
            # signal (the #10411/#10403 class), not a human-judgment need. Route
            # it straight to the Auto-Agent's autofix stage rather than the
            # human-visible HITL queue (flag-gated, default on); the Auto-Agent
            # decomposes/retries and only pages a human (``human-required``) if
            # it too exhausts.
            human_visible = not self._config.diagnostic_exhausted_routes_autofix
            logger.info(
                "Diagnostic: issue #%d exhausted %d attempt(s) — routing to %s",
                issue_number,
                len(attempts),
                "HITL (human-visible)" if human_visible else "Auto-Agent autofix",
            )
            await self._escalate_to_hitl(
                issue_number,
                comment=diagnosis_comment,
                human_visible=human_visible,
            )
            return "escalated"

        return None

    async def _attempt_fix(
        self,
        issue_number: int,
        issue_title: str,
        issue_body: str,
        diagnosis: DiagnosisResult,
        attempts: list[AttemptRecord],
        diagnosis_comment: str,
        issue_labels: Sequence[str] = (),
    ) -> str:
        """Stage 2: provision a workspace, run the fix, and finalize the outcome.

        Returns ``"fixed"``, ``"retry"``, or ``"escalated"``.
        """
        logger.info(
            "Diagnostic: running Stage 2 (fix) for issue #%d (attempt %d of %d)",
            issue_number,
            len(attempts) + 1,
            self._config.max_diagnostic_attempts,
        )
        await self._publish_update(issue_number, "fixing")

        wt_path = await self._prepare_fix_workspace(issue_number, diagnosis_comment)
        if wt_path is None:
            return "escalated"

        success, transcript = await self._run_fix(
            issue_number, issue_title, issue_body, diagnosis, wt_path, issue_labels
        )
        self._record_attempt(issue_number, attempts, success, transcript)
        return await self._finalize_fix_outcome(
            issue_number, success, diagnosis_comment
        )

    async def _prepare_fix_workspace(
        self, issue_number: int, diagnosis_comment: str
    ) -> Path | None:
        """Return the worktree path for the fix, creating it if needed.

        Returns ``None`` (after escalating to HITL) when workspace creation
        fails.
        """
        branch = f"agent/diag-{issue_number}"
        wt_path = self._config.workspace_path_for_issue(issue_number)
        if self._workspaces is not None and not wt_path.exists():
            try:
                wt_path = await self._workspaces.create(issue_number, branch)
            except Exception:
                logger.exception(
                    "Diagnostic: workspace creation failed for issue #%d",
                    issue_number,
                )
                await self._escalate_to_hitl(issue_number, comment=diagnosis_comment)
                return None
        return wt_path

    async def _run_fix(
        self,
        issue_number: int,
        issue_title: str,
        issue_body: str,
        diagnosis: DiagnosisResult,
        wt_path: Path,
        issue_labels: Sequence[str] = (),
    ) -> tuple[bool, str]:
        """Run the fix agent and clean up the workspace on failure.

        Returns ``(success, transcript)``. Infra-level failures (auth, credit,
        OS) propagate; other exceptions are logged and treated as a failed fix.
        """
        try:
            success, transcript = await self._runner.fix(
                issue_number,
                issue_title,
                issue_body,
                diagnosis,
                str(wt_path),
                issue_labels=issue_labels,
            )
        except Exception as exc:
            # Infra-level failures (auth, credit, OS permission/IO) propagate
            # so the cycle aborts cleanly rather than burning attempt budget
            # on a permanent error (#6411). Programming errors and other
            # Exception subclasses are logged with exc_info and treated as a
            # failed fix so the diagnostic loop can continue with the next
            # issue (#6606).
            from subprocess_util import (  # noqa: PLC0415
                AuthenticationError,
                CreditExhaustedError,
            )

            if isinstance(exc, AuthenticationError | CreditExhaustedError | OSError):
                raise
            logger.exception(
                "Diagnostic: runner.fix() crashed for issue #%d",
                issue_number,
            )
            success, transcript = False, "runner.fix() crashed"

        # Only destroy the workspace on failure (#6477). When the fix
        # succeeds the worktree contains the committed changes that the
        # review phase must read — destroying here was producing a
        # zero-commit error in the review phase.
        if not success and self._workspaces is not None:
            try:
                await self._workspaces.destroy(issue_number)
            except Exception:
                logger.warning(
                    "Diagnostic: workspace cleanup failed for issue #%d",
                    issue_number,
                    exc_info=True,
                )

        return success, transcript

    def _record_attempt(
        self,
        issue_number: int,
        attempts: list[AttemptRecord],
        success: bool,
        transcript: str,
    ) -> None:
        """Persist an AttemptRecord for this fix attempt regardless of outcome."""
        record = AttemptRecord(
            attempt_number=len(attempts) + 1,
            changes_made=success,
            error_summary=(
                "" if success else (transcript[:200] if transcript else "fix failed")
            ),
            timestamp=datetime.now(UTC).isoformat(),
        )
        self._state.add_diagnostic_attempt(issue_number, record)

    async def _finalize_fix_outcome(
        self, issue_number: int, success: bool, diagnosis_comment: str
    ) -> str:
        """Transition to review on success, else retry or escalate.

        Returns ``"fixed"``, ``"retry"``, or ``"escalated"``.
        """
        if success:
            logger.info(
                "Diagnostic: fix succeeded for issue #%d — transitioning to review",
                issue_number,
            )
            await self._prs.post_comment(
                issue_number,
                (
                    "## Diagnostic Fix Applied\n\n"
                    "The diagnostic agent successfully applied a fix.\n\n"
                    f"{diagnosis_comment}"
                ),
            )
            try:
                await self._prs.swap_pipeline_labels(
                    issue_number, self._config.review_label[0]
                )
            except Exception:
                logger.warning(
                    "Diagnostic: label swap to review failed for issue #%d "
                    "— fix was applied but issue may need manual label update",
                    issue_number,
                    exc_info=True,
                )
            await self._publish_update(issue_number, "fixed")
            return "fixed"

        # Fix failed — check if we still have attempts remaining after recording
        attempts_after = self._state.get_diagnostic_attempts(issue_number)
        if len(attempts_after) < self._config.max_diagnostic_attempts:
            # Will retry next cycle — leave on diagnose label
            logger.info(
                "Diagnostic: fix attempt %d failed for issue #%d — will retry next cycle",
                len(attempts_after),
                issue_number,
            )
            await self._publish_update(issue_number, "retry")
            return "retry"

        # All attempts exhausted after this failure — same auto-resolvable
        # "too-big / wrong-strategy" signal as the pre-fix gate (#10411/#10403):
        # route to the Auto-Agent autofix stage, not the human-visible queue.
        human_visible = not self._config.diagnostic_exhausted_routes_autofix
        logger.info(
            "Diagnostic: fix failed and attempts exhausted for issue #%d — routing to %s",
            issue_number,
            "HITL (human-visible)" if human_visible else "Auto-Agent autofix",
        )
        await self._escalate_to_hitl(
            issue_number, comment=diagnosis_comment, human_visible=human_visible
        )
        return "escalated"

    async def _escalate_to_hitl(
        self, issue_number: int, *, comment: str, human_visible: bool = True
    ) -> None:
        """Post the diagnosis comment and route to HITL via the Auto-Agent.

        The diagnose phase couldn't resolve this, but rather than dead-end at a
        human we first route it into the Auto-Agent's convergence loop
        (ADR-0084): ``hydraflow-hitl`` keeps it visible in the HITL queue, and
        ``hitl-escalation`` + ``diagnose-failed`` make ``AutoAgentPreflightLoop``
        discover it and attempt a root-cause fix — retrying a transient (e.g. a
        credit/session limit) or applying the diagnosis — before any human is
        involved. The Auto-Agent routes a *resolved* diagnose-failed issue back
        to review.

        *human_visible* (#10411/#10403 HITL-transit fix): when ``False`` (the
        attempts-exhausted gate — an auto-resolvable "too-big scope" signal, NOT
        a human-judgment need), swap straight to the ``hydraflow-hitl-autofix``
        claim stage instead of ``hydraflow-hitl``. The Auto-Agent poll covers
        BOTH stages, so it still discovers + decomposes the issue, but it is
        excluded from the human queue (built from ``hitl``/``hitl-active`` only)
        from the start rather than transiting it for a poll cycle. If the
        Auto-Agent ALSO exhausts, it applies ``human-required`` — so the human
        fallback is preserved. ``True`` (not-fixable / missing-context — genuine
        judgment) keeps the issue human-visible as before.
        """
        digest = hashlib.sha256(comment.encode("utf-8")).hexdigest()[:16]
        dedup_key = f"{issue_number}:{digest}"
        seen = self._hitl_comment_dedup.get()
        if dedup_key in seen:
            logger.info(
                "Diagnostic: identical diagnosis comment already posted on "
                "issue #%d — skipping re-post (labels still applied)",
                issue_number,
            )
        else:
            try:
                await self._prs.post_comment(issue_number, comment)
            except Exception:
                logger.warning(
                    "Diagnostic: failed to post comment for issue #%d",
                    issue_number,
                    exc_info=True,
                )
            else:
                # Replace any previous hash for this issue: bounded at one
                # key per issue, and a CHANGED diagnosis re-posts.
                prefix = f"{issue_number}:"
                self._hitl_comment_dedup.set_all(
                    {k for k in seen if not k.startswith(prefix)} | {dedup_key}
                )
        stage_label = (
            self._config.hitl_label[0]
            if human_visible
            else self._config.hitl_autofix_label[0]
        )
        try:
            await self._prs.swap_pipeline_labels(issue_number, stage_label)
        except Exception:
            logger.warning(
                "Diagnostic: label swap to %s failed for issue #%d "
                "— issue may need manual label update",
                stage_label,
                issue_number,
                exc_info=True,
            )
        # Route into the Auto-Agent convergence loop. ``hitl-escalation`` is not
        # a pipeline-stage label, so it survives the swap above — the issue then
        # carries both ``hydraflow-hitl`` (HITL queue) and the Auto-Agent
        # routing labels.
        #
        # #10262: guard the re-arm. If a *prior* attempt's resolving PR is
        # already open, reconciliation (the Auto-Agent routes a resolved
        # ``diagnose-failed`` issue back to review) has just cleared these
        # labels. Re-adding them here — including on the comment-dedup hit path
        # above ("labels still applied") — flaps the labels and renews
        # auto-agent dispatch pressure. Defer to the reconciler's verdict and
        # skip the re-arm when an open resolving PR exists. Conservative: any
        # lookup failure falls through to today's escalate behaviour.
        if await self._has_open_resolving_pr(issue_number):
            logger.info(
                "Diagnostic: open resolving PR exists for issue #%d — skipping "
                "hitl-escalation/diagnose-failed re-arm (deferring to the "
                "reconciler)",
                issue_number,
            )
        else:
            try:
                await self._prs.add_labels(
                    issue_number, ["hitl-escalation", "diagnose-failed"]
                )
            except Exception:
                logger.warning(
                    "Diagnostic: failed to add Auto-Agent routing labels for #%d",
                    issue_number,
                    exc_info=True,
                )
        await self._publish_update(issue_number, "escalated")

    async def _has_open_resolving_pr(self, issue_number: int) -> bool:
        """Return whether an open PR already resolves *issue_number*.

        Uses the same branch-convention signal the reconciler consults —
        ``find_open_pr_for_branch`` on the canonical ``agent/issue-{N}``
        branch. A prior diagnostic/auto-agent attempt that pushed a fix opens
        such a PR; the Auto-Agent then routes the resolved issue back to review
        and clears the escalation labels. On any lookup error this returns
        ``False`` (fail-open to the escalate behaviour) after re-raising
        credit/bug signals per the dark-factory contract.
        """
        try:
            pr = await self._prs.find_open_pr_for_branch(
                self._config.branch_for_issue(issue_number),
                issue_number=issue_number,
            )
        except Exception as exc:
            reraise_on_credit_or_bug(exc)
            logger.warning(
                "Diagnostic: open-PR lookup failed for issue #%d — proceeding "
                "with escalation",
                issue_number,
                exc_info=True,
            )
            return False
        # FakeGitHub returns ``PRInfo(number=0)`` as an absence sentinel; the
        # real PRManager returns ``None``. Both mean "no open resolving PR".
        return pr is not None and pr.number > 0

    async def _publish_update(self, issue_number: int, status: str) -> None:
        """Publish a DIAGNOSTIC_UPDATE event for dashboard visibility."""
        await self._bus.publish(
            HydraFlowEvent(
                type=EventType.DIAGNOSTIC_UPDATE,
                data={"issue": issue_number, "status": status},
            )
        )
