"""Create an epic + child issues from a decomposition result and register it.

Extracted from ``TriagePhase._maybe_decompose`` (behavior-preserving, #ADR-0105
decompose-to-converge) so both the intake-triage decomposition path and a
later auto-agent decompose-on-stall path can share the same create/link/
register plumbing.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from config import HydraFlowConfig
    from epic import EpicManager
    from models import EpicDecompResult, Task
    from ports import PRPort
    from state import StateTracker

logger = logging.getLogger("hydraflow.issue_decomposer")


class IssueDecomposer:
    """Creates an epic + child issues from an ``EpicDecompResult`` and registers it."""

    def __init__(
        self,
        prs: PRPort,
        epic_manager: EpicManager,
        state: StateTracker,
        config: HydraFlowConfig,
    ) -> None:
        self._prs = prs
        self._epic_manager = epic_manager
        self._state = state
        self._config = config

    async def create_epic_from_result(
        self,
        *,
        source_task: Task,
        result: EpicDecompResult,
        depth: int = 0,
        stall_context: str | None = None,
    ) -> int | None:
        """Create an epic + children from *result*, register it, close *source_task*.

        Returns the new epic issue number, or ``None`` when
        ``result.should_decompose`` is False or the epic issue failed to
        create. When *stall_context* is set, it is embedded into every child
        body (used by the auto-agent decompose-on-stall path to carry
        forward why the parent stalled). *depth* is recorded on the new
        epic's ``EpicState.decomposition_depth``.
        """
        if not result.should_decompose:
            return None

        epic_label = self._config.epic_label[0]
        epic_child_label = self._config.epic_child_label[0]
        find_label = self._config.find_label[0]

        # Create the epic issue
        epic_number = await self._prs.create_issue(
            result.epic_title,
            result.epic_body,
            [epic_label],
        )
        if epic_number <= 0:
            logger.warning(
                "Failed to create epic issue for decomposition of #%d",
                source_task.id,
            )
            return None

        # Create child issues
        child_numbers: list[int] = []
        for child_spec in result.children:
            child_body = child_spec.body + f"\n\nParent Epic #{epic_number}"
            if stall_context:
                child_body += f"\n\n{stall_context}"
            child_num = await self._prs.create_issue(
                child_spec.title,
                child_body,
                [epic_child_label, find_label],
            )
            if child_num > 0:
                child_numbers.append(child_num)
                self._state.record_issue_created()

        # Register with EpicManager
        await self._epic_manager.register_epic(
            epic_number,
            result.epic_title,
            child_numbers,
            auto_decomposed=True,
        )

        if depth:
            epic_state = self._state.get_epic_state(epic_number)
            if epic_state is not None:
                epic_state.decomposition_depth = depth
                self._state.upsert_epic_state(epic_state)

        # Close the original issue with a link to the epic
        await self._prs.post_comment(
            source_task.id,
            f"## Auto-Decomposed into Epic\n\n"
            f"This issue was automatically decomposed into epic #{epic_number} "
            f"with {len(child_numbers)} child issue(s).\n\n"
            f"**Reason:** {result.reasoning}\n\n"
            f"---\n*Generated by HydraFlow Triage*",
        )
        await self._prs.close_issue(source_task.id)
        self._state.mark_issue(source_task.id, "decomposed")

        logger.info(
            "Issue #%d decomposed into epic #%d with %d children: %s",
            source_task.id,
            epic_number,
            len(child_numbers),
            child_numbers,
        )
        return epic_number
