"""Outcome disposition of :class:`plan_phase.PlanPhase`.

Extracted VERBATIM from ``plan_phase.py`` (god-class decomposition, Refs
#11547) as a mixin; ``PlanPhase`` inherits :class:`PlanDispositionMixin`.

One cohesive concern: where an issue goes once planning has an answer —
already-satisfied close, the ADR-0002 swap to ``hydraflow-ready`` (plus filing
discovered sub-issues), the #10659 design-decision route to
``human-required``, HITL escalation on failure, and the transcript /
memory-suggestion tail every path posts.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from harness_insights import FailureCategory
from models import IssueOutcomeType, PlanResult, Task
from pending_concerns import Concern, is_design_decision_concern
from plan_phase_common import _MIN_ISSUE_BODY_CHARS
from planner import PlannerRunner

if TYPE_CHECKING:
    from config import HydraFlowConfig
    from phase_utils import MemorySuggester, PipelineEscalator
    from ports import IssueStorePort, PRPort
    from state import StateTracker
    from task_source import TaskTransitioner
    from transcript_summarizer import TranscriptSummarizer

# Same logger as the host — the moved code's records keep their
# pre-extraction ``hydraflow.plan_phase`` origin.
logger = logging.getLogger("hydraflow.plan_phase")


class PlanDispositionMixin:
    """Outcome disposition of :class:`plan_phase.PlanPhase`."""

    # ------------------------------------------------------------------
    # Collaborator seams — attributes and methods provided by PlanPhase or a
    # sibling mixin. The method declarations are TYPE_CHECKING-only on
    # purpose: a runtime ``...`` body would take precedence over the real
    # implementation whenever the declaring mixin precedes the implementing
    # one in the host's MRO (#11629).
    # ------------------------------------------------------------------
    _config: HydraFlowConfig
    _escalator: PipelineEscalator
    _prs: PRPort
    _state: StateTracker
    _store: IssueStorePort
    _suggest_memory: MemorySuggester
    _summarizer: TranscriptSummarizer | None
    _transitioner: TaskTransitioner

    async def _handle_already_satisfied(self, issue: Task, result: PlanResult) -> bool:
        """Validate evidence and close issue as already-satisfied.

        Returns ``True`` if the issue was closed, ``False`` if evidence validation
        failed (caller should fall through to plan failure handling).
        """
        validation_errors = PlannerRunner.validate_already_satisfied_evidence(
            result.summary,
            issue_body=issue.body,
            repo_root=self._config.repo_root,
        )
        if validation_errors:
            error_list = "\n".join(f"- {e}" for e in validation_errors)
            await self._transitioner.post_comment(
                issue.id,
                f"## Already-Satisfied Evidence Rejected\n\n"
                f"The planner claimed this issue is already satisfied, but the "
                f"evidence failed validation:\n\n{error_list}\n\n"
                f"The issue will be escalated for review.\n\n"
                f"---\n"
                f"*Generated by HydraFlow Planner*",
            )
            result.already_satisfied = False
            result.success = False
            result.retry_attempted = True
            result.validation_errors = validation_errors
            result.error = "Already-satisfied evidence rejected: " + "; ".join(
                validation_errors
            )
            logger.warning(
                "Issue #%d already-satisfied evidence rejected: %s",
                issue.id,
                "; ".join(validation_errors),
            )
            return False

        await self._prs.swap_pipeline_labels(issue.id, self._config.dup_label[0])
        await self._transitioner.post_comment(
            issue.id,
            f"## Already Satisfied\n\n"
            f"The planner determined that this issue's requirements "
            f"are already met by the existing codebase.\n\n"
            f"{result.summary}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*",
        )
        await self._transitioner.close_task(issue.id)
        self._state.record_outcome(
            issue.id,
            IssueOutcomeType.ALREADY_SATISFIED,
            reason=result.summary,
            phase="plan",
        )
        self._state.increment_session_counter("planned")
        logger.info("Issue #%d closed as already satisfied", issue.id)
        if self._summarizer and result.transcript:
            try:
                await self._summarizer.summarize_and_comment(
                    transcript=result.transcript,
                    issue_number=issue.id,
                    phase="plan",
                    status="success",
                    issue_title=issue.title,
                    duration_seconds=result.duration_seconds,
                    log_file=self._plan_log_reference(issue.id),
                    issue_labels=issue.tags,
                )
            except (RuntimeError, OSError):
                logger.exception(
                    "Failed to post transcript summary for issue #%d", issue.id
                )
        return True

    async def _swap_plan_to_ready(self, issue: Task, result: PlanResult) -> None:
        """Swap the issue to ``hydraflow-ready`` and file discovered sub-issues.

        The post-gate half of the former ``_handle_plan_success`` (P3a of
        #10682). Reached from the ``ready`` flow node only when the #10659
        design-decision ``gate`` did NOT route the issue to ``human-required``.
        """
        # Activate eager-transition protection BEFORE the GitHub label swap
        # so that concurrent polling cannot re-queue the issue during the
        # non-atomic label add/remove window.
        self._store.enqueue_transition(issue, "ready")
        await self._transitioner.transition(issue.id, "ready")

        for new_issue in result.new_issues:
            if len(new_issue.body) < _MIN_ISSUE_BODY_CHARS:
                logger.warning(
                    "Skipping discovered issue %r — body too short "
                    "(%d chars, need ≥%d)",
                    new_issue.title,
                    len(new_issue.body),
                    _MIN_ISSUE_BODY_CHARS,
                )
                continue
            labels = new_issue.labels or [self._config.planner_label[0]]
            await self._transitioner.create_task(
                new_issue.title, new_issue.body, labels
            )
            self._state.record_issue_created()

        if result.duration_seconds > 0:
            self._state.record_plan_duration(result.duration_seconds)
        self._state.increment_session_counter("planned")
        logger.info("Plan posted and labels swapped for issue #%d", issue.id)

    async def _route_to_hitl_if_design_decision(self, issue: Task) -> bool:
        """Route to ``human-required`` when plan review needs a human decision.

        Issue #10659: when the accumulated ``AdversarialState`` for *issue*
        holds at least ``plan_design_decision_hitl_threshold`` design-decision-
        class CRITICAL concerns (unresolved design decision / unvalidated core
        mechanism — see ``is_design_decision_concern``), the issue is NOT ready
        to implement. Swap it to ``human-required`` (which is orthogonal to the
        stage machine and skipped by every pipeline queue) instead of
        ``hydraflow-ready``, post an explanatory comment listing the concerns,
        and clear the adversarial state so a post-design re-queue starts fresh.

        Returns ``True`` when the issue was routed to HITL (caller must NOT
        proceed to the ready swap), ``False`` otherwise (normal flow to ready).
        """
        adv = self._state.get_adversarial_state(issue.id)
        if adv is None:
            return False
        design_concerns: list[Concern] = [
            c for c in adv.pending_concerns if is_design_decision_concern(c)
        ]
        threshold = self._config.plan_design_decision_hitl_threshold
        if len(design_concerns) < threshold:
            return False

        concern_lines = "\n".join(
            f"- **[{c.severity}|{c.raised_in_stage}]** {c.concern}"
            for c in design_concerns
        )
        comment = (
            "## Design decision required — routed to `human-required`\n\n"
            f"Plan review surfaced **{len(design_concerns)}** unresolved "
            "design-decision / unvalidated-core-mechanism concern(s) "
            f"(threshold: {threshold}). These need a human decision "
            "(brainstorm → spec) before implementation — forwarding them to the "
            "implementer causes the build agent to hang to the timeout and "
            "retry-thrash on an underspecified feature (#10659).\n\n"
            f"{concern_lines}\n\n"
            "Re-apply a pipeline label once the design is decided.\n\n"
            "---\n*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(issue.id, comment)
        # Clear adversarial state before the HITL hand-off so a post-design
        # re-queue starts fresh (mirrors the other HITL escalation paths) —
        # otherwise pending_concerns grows unboundedly across cycles.
        self._state.clear_adversarial_state(issue.id)
        await self._prs.swap_pipeline_labels(issue.id, "human-required")
        logger.warning(
            "Issue #%d routed to human-required — %d design-decision CRITICAL "
            "concern(s) >= threshold %d (not swapping to ready)",
            issue.id,
            len(design_concerns),
            threshold,
        )
        return True

    # _wiki_ingest_plan / _wiki_tracked_store / _precompute_corroboration /
    # _wiki_commit_compiler_entries are provided by PlanWikiIngestMixin
    # (plan_phase_wiki_ingest.py) — extracted verbatim, #10840.

    async def _handle_plan_failure(self, issue: Task, result: PlanResult) -> None:
        """Post comment, escalate to HITL, record harness failure."""
        error_list = "\n".join(f"- {e}" for e in result.validation_errors)
        score_line = ""
        if result.actionability_rank != "unknown":
            score_line = (
                f"**Actionability score:** {result.actionability_score}/100 "
                f"({result.actionability_rank})\n\n"
            )
        hitl_comment = (
            f"## Plan Validation Failed\n\n"
            f"The planner was unable to produce a valid plan "
            f"after planning attempts for issue #{issue.id}.\n\n"
            f"{score_line}"
            f"**Validation errors:**\n{error_list}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(issue.id, hitl_comment)
        # Clear any accumulated adversarial state before HITL hand-off. Next
        # retry (after operator re-labels to hydraflow-ready) starts with a
        # fresh AdversarialState — otherwise the surfacer's concerns would
        # be appended on top of the prior attempt's, growing unboundedly
        # across HITL cycles.
        self._state.clear_adversarial_state(issue.id)
        await self._escalator(
            issue,
            cause="Plan validation failed after retry",
            details="; ".join(result.validation_errors),
            category=FailureCategory.PLAN_VALIDATION,
        )
        logger.warning(
            "Planning failed validation for issue #%d after retry — escalated to HITL",
            issue.id,
        )

    async def _post_plan_transcript(
        self, issue: Task, result: PlanResult, *, status: str
    ) -> None:
        """File memory suggestion and post transcript summary."""
        if result.transcript:
            await self._suggest_memory(
                result.transcript, "planner", f"issue #{issue.id}"
            )
        if self._summarizer and result.transcript:
            try:
                await self._summarizer.summarize_and_comment(
                    transcript=result.transcript,
                    issue_number=issue.id,
                    phase="plan",
                    status=status,
                    issue_title=issue.title,
                    duration_seconds=result.duration_seconds,
                    log_file=self._plan_log_reference(issue.id),
                    issue_labels=issue.tags,
                )
            except (RuntimeError, OSError):
                logger.exception(
                    "Failed to post transcript summary for issue #%d", issue.id
                )

    def _plan_log_reference(self, issue_number: int) -> str:
        """Return a display-friendly log path for planner transcripts."""
        log_path = self._config.log_dir / f"plan-issue-{issue_number}.txt"
        return self._config.format_path_for_display(log_path)
