"""Outcome disposition of :class:`plan_phase.PlanPhase`.

Extracted VERBATIM from ``plan_phase.py`` (god-class decomposition, Refs
#11547) as a mixin; ``PlanPhase`` inherits :class:`PlanDispositionMixin`.

One cohesive concern: where an issue goes once planning has an answer —
already-satisfied close, the ADR-0002 swap to ``hydraflow-ready`` (plus filing
discovered sub-issues), the #10659 design-decision route to
``human-required``, HITL escalation on failure, and the transcript /
memory-suggestion tail every path posts.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, cast

from exception_classify import reraise_on_credit_or_bug
from harness_insights import FailureCategory
from issue_decomposer import IssueDecomposer
from models import IssueOutcomeType, PlanResult, Task
from pending_concerns import Concern, is_design_decision_concern
from plan_phase_common import _MIN_ISSUE_BODY_CHARS
from plan_validation import rejection_class
from planner import PlannerRunner
from preflight.context import PreflightContext
from preflight.decompose_terminal import decompose_or_escalate

if TYPE_CHECKING:
    from config import HydraFlowConfig
    from phase_utils import MemorySuggester, PipelineEscalator
    from ports import IssueStorePort, PRPort
    from state import StateTracker
    from task_source import TaskTransitioner
    from transcript_summarizer import TranscriptSummarizer

# Same logger as the host — the moved code's records keep their
# pre-extraction ``hydraflow.plan_phase`` origin.
logger = logging.getLogger("hydraflow.plan_phase")


class PlanDispositionMixin:
    """Outcome disposition of :class:`plan_phase.PlanPhase`."""

    # ------------------------------------------------------------------
    # Collaborator seams — attributes and methods provided by PlanPhase or a
    # sibling mixin. The method declarations are TYPE_CHECKING-only on
    # purpose: a runtime ``...`` body would take precedence over the real
    # implementation whenever the declaring mixin precedes the implementing
    # one in the host's MRO (#11629).
    # ------------------------------------------------------------------
    _config: HydraFlowConfig
    _escalator: PipelineEscalator
    _prs: PRPort
    _state: StateTracker
    _store: IssueStorePort
    _suggest_memory: MemorySuggester
    _summarizer: TranscriptSummarizer | None
    _transitioner: TaskTransitioner

    async def _handle_already_satisfied(self, issue: Task, result: PlanResult) -> bool:
        """Validate evidence and close issue as already-satisfied.

        Returns ``True`` if the issue was closed, ``False`` if evidence validation
        failed (caller should fall through to plan failure handling).
        """
        validation_errors = PlannerRunner.validate_already_satisfied_evidence(
            result.summary,
            issue_body=issue.body,
            repo_root=self._config.repo_root,
        )
        if validation_errors:
            error_list = "\n".join(f"- {e}" for e in validation_errors)
            await self._transitioner.post_comment(
                issue.id,
                f"## Already-Satisfied Evidence Rejected\n\n"
                f"The planner claimed this issue is already satisfied, but the "
                f"evidence failed validation:\n\n{error_list}\n\n"
                f"The issue will be escalated for review.\n\n"
                f"---\n"
                f"*Generated by HydraFlow Planner*",
            )
            result.already_satisfied = False
            result.success = False
            result.retry_attempted = True
            result.validation_errors = validation_errors
            result.error = "Already-satisfied evidence rejected: " + "; ".join(
                validation_errors
            )
            logger.warning(
                "Issue #%d already-satisfied evidence rejected: %s",
                issue.id,
                "; ".join(validation_errors),
            )
            return False

        await self._prs.swap_pipeline_labels(issue.id, self._config.dup_label[0])
        await self._transitioner.post_comment(
            issue.id,
            f"## Already Satisfied\n\n"
            f"The planner determined that this issue's requirements "
            f"are already met by the existing codebase.\n\n"
            f"{result.summary}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*",
        )
        await self._transitioner.close_task(issue.id)
        self._state.record_outcome(
            issue.id,
            IssueOutcomeType.ALREADY_SATISFIED,
            reason=result.summary,
            phase="plan",
        )
        self._state.increment_session_counter("planned")
        logger.info("Issue #%d closed as already satisfied", issue.id)
        if self._summarizer is not None and result.transcript:
            try:
                await self._summarizer.summarize_and_comment(
                    transcript=result.transcript,
                    issue_number=issue.id,
                    phase="plan",
                    status="success",
                    issue_title=issue.title,
                    duration_seconds=result.duration_seconds,
                    log_file=self._plan_log_reference(issue.id),
                    issue_labels=issue.tags,
                )
            except (RuntimeError, OSError) as exc:
                # CreditExhaustedError/AuthenticationError subclass RuntimeError,
                # so this clause would otherwise bury the one failure the loop
                # must pause on (#6855 class, #11666 audit sweep).
                reraise_on_credit_or_bug(exc)
                logger.exception(
                    "Failed to post transcript summary for issue #%d", issue.id
                )
        return True

    async def _swap_plan_to_ready(self, issue: Task, result: PlanResult) -> None:
        """Swap the issue to ``hydraflow-ready`` and file discovered sub-issues.

        The post-gate half of the former ``_handle_plan_success`` (P3a of
        #10682). Reached from the ``ready`` flow node only when the #10659
        design-decision ``gate`` did NOT route the issue to ``human-required``.
        """
        # Activate eager-transition protection BEFORE the GitHub label swap
        # so that concurrent polling cannot re-queue the issue during the
        # non-atomic label add/remove window.
        self._store.enqueue_transition(issue, "ready")
        await self._transitioner.transition(issue.id, "ready")

        for new_issue in result.new_issues:
            if len(new_issue.body) < _MIN_ISSUE_BODY_CHARS:
                logger.warning(
                    "Skipping discovered issue %r — body too short "
                    "(%d chars, need ≥%d)",
                    new_issue.title,
                    len(new_issue.body),
                    _MIN_ISSUE_BODY_CHARS,
                )
                continue
            labels = new_issue.labels or [self._config.planner_label[0]]
            await self._transitioner.create_task(
                new_issue.title, new_issue.body, labels
            )
            self._state.record_issue_created()

        if result.duration_seconds > 0:
            self._state.record_plan_duration(result.duration_seconds)
        self._state.increment_session_counter("planned")
        logger.info("Plan posted and labels swapped for issue #%d", issue.id)

    async def _route_to_hitl_if_design_decision(self, issue: Task) -> bool:
        """Route to ``human-required`` when plan review needs a human decision.

        Issue #10659: when the accumulated ``AdversarialState`` for *issue*
        holds at least ``plan_design_decision_hitl_threshold`` design-decision-
        class CRITICAL concerns (unresolved design decision / unvalidated core
        mechanism — see ``is_design_decision_concern``), the issue is NOT ready
        to implement. Swap it to ``human-required`` (which is orthogonal to the
        stage machine and skipped by every pipeline queue) instead of
        ``hydraflow-ready``, post an explanatory comment listing the concerns,
        and clear the adversarial state so a post-design re-queue starts fresh.

        Returns ``True`` when the issue was routed to HITL (caller must NOT
        proceed to the ready swap), ``False`` otherwise (normal flow to ready).
        """
        adv = self._state.get_adversarial_state(issue.id)
        if adv is None:
            return False
        design_concerns: list[Concern] = [
            c for c in adv.pending_concerns if is_design_decision_concern(c)
        ]
        threshold = self._config.plan_design_decision_hitl_threshold
        if len(design_concerns) < threshold:
            return False

        concern_lines = "\n".join(
            f"- **[{c.severity}|{c.raised_in_stage}]** {c.concern}"
            for c in design_concerns
        )
        comment = (
            "## Design decision required — routed to `human-required`\n\n"
            f"Plan review surfaced **{len(design_concerns)}** unresolved "
            "design-decision / unvalidated-core-mechanism concern(s) "
            f"(threshold: {threshold}). These need a human decision "
            "(brainstorm → spec) before implementation — forwarding them to the "
            "implementer causes the build agent to hang to the timeout and "
            "retry-thrash on an underspecified feature (#10659).\n\n"
            f"{concern_lines}\n\n"
            "Re-apply a pipeline label once the design is decided.\n\n"
            "---\n*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(issue.id, comment)
        # Clear adversarial state before the HITL hand-off so a post-design
        # re-queue starts fresh (mirrors the other HITL escalation paths) —
        # otherwise pending_concerns grows unboundedly across cycles.
        self._state.clear_adversarial_state(issue.id)
        await self._prs.swap_pipeline_labels(issue.id, "human-required")
        logger.warning(
            "Issue #%d routed to human-required — %d design-decision CRITICAL "
            "concern(s) >= threshold %d (not swapping to ready)",
            issue.id,
            len(design_concerns),
            threshold,
        )
        return True

    # _wiki_ingest_plan / _wiki_tracked_store / _precompute_corroboration /
    # _wiki_commit_compiler_entries are provided by PlanWikiIngestMixin
    # (plan_phase_wiki_ingest.py) — extracted verbatim, #10840.

    def _plan_rejections_exhausted(
        self, issue_number: int, errors: list[str]
    ) -> tuple[bool, str, int]:
        """Has one gate now refused this issue enough times to stop asking?

        Counts per REJECTION CLASS, not in total (#11822, operator ruling).
        Three refusals from the same gate is an issue the planner cannot
        shrink — #11544 lost nine of its eleven attempts to the duplicate
        enforcement-test gate alone. Three different gates once each is an
        issue with three fixable faults, and routing that to decomposition
        would split work that only needed correcting.

        Counts HITL round-trips, not retries. The planner already retries once
        with the validation errors in its prompt and then hands off, so each
        rejection here is a separate cycle that began with no memory of the
        last. The counts live on the convergence ledger because
        `clear_adversarial_state` runs at every hand-off and would otherwise
        wipe them before the second cycle could see the first.

        Returns ``(exhausted, worst_class, count)``.
        """
        threshold = self._config.plan_validation_decompose_threshold
        worst_class, worst = "", 0
        for cls in {rejection_class(e) for e in errors}:
            n = self._state.bump_plan_validation_rejection(issue_number, cls)
            if n > worst:
                worst_class, worst = cls, n
        if threshold <= 0:
            return False, worst_class, worst
        return worst >= threshold, worst_class, worst

    async def _route_to_decomposition(self, issue: Task, worst_class: str) -> bool:
        """Split the issue instead of asking the planner again (#11822).

        Returns True when the issue was superseded by an epic, in which case
        the caller must NOT also escalate — the issue is no longer waiting on
        a human, it is waiting on its children.

        Degrades to False whenever decomposition is not wired or declines, so
        every path that reaches here still lands on today's HITL behaviour.
        That is deliberate: a gate refusing an oversized plan is a correct
        refusal, and if we cannot split the issue a human is the right next
        step — this must never swallow the escalation.
        """
        epic_manager = getattr(self, "_epic_manager", None)
        ensemble = getattr(self, "_decomposition_ensemble", None)
        if epic_manager is None or ensemble is None:
            return False

        ctx = PreflightContext(
            issue_number=issue.id,
            issue_body=issue.body or "",
            issue_comments=[],
            sub_label=self._config.planner_label[0],
            escalation_context=None,
            wiki_excerpts="",
            sentry_events=[],
            recent_commits=[],
        )
        try:
            outcome = await decompose_or_escalate(
                issue_number=issue.id,
                ctx=ctx,
                config=self._config,
                decomposer=IssueDecomposer(
                    self._prs, epic_manager, self._state, self._config
                ),
                ensemble=ensemble,
                state=self._state,
                # `decompose_terminal._PRPort` names members `PRPort` does not
                # have (`get_pr_reviews`) and types `close_pr` as returning
                # None where ours returns bool, so the declared protocol does
                # not describe its real caller. AutoAgentPreflightLoop passes
                # this same object and only typechecks because it declares
                # `pr_manager: Any`. Passing it the same way rather than
                # loosening another module's protocol from here.
                prs=cast("Any", self._prs),
            )
        except (RuntimeError, OSError, ValueError) as exc:
            # Narrower than a blind catch because the suppressions ratchet only
            # shrinks, and narrower is also more honest here: everything
            # reachable from `decompose_or_escalate` — the ensemble's spawn, the
            # PR reads, the epic writes — surfaces as one of these. A TypeError
            # or AttributeError from this call is a bug in the wiring above, and
            # should reach the loop's own handler rather than be logged as a
            # failed decomposition. `reraise_on_credit_or_bug` still earns its
            # place: CreditExhausted and Authentication are RuntimeError
            # subclasses and would otherwise be swallowed into the fallback.
            reraise_on_credit_or_bug(exc)
            logger.warning(
                "Decomposition route failed for issue #%d — falling back to HITL",
                issue.id,
                exc_info=True,
            )
            return False

        if outcome != "decomposed":
            return False

        self._state.clear_plan_validation_rejections(issue.id)
        logger.warning(
            "Issue #%d decomposed after %r refused it %d times — not escalating",
            issue.id,
            worst_class,
            self._config.plan_validation_decompose_threshold,
        )
        return True

    async def _handle_plan_failure(self, issue: Task, result: PlanResult) -> None:
        """Post comment, escalate to HITL, record harness failure."""
        error_list = "\n".join(f"- {e}" for e in result.validation_errors)
        score_line = ""
        if result.actionability_rank != "unknown":
            score_line = (
                f"**Actionability score:** {result.actionability_score}/100 "
                f"({result.actionability_rank})\n\n"
            )
        exhausted, worst_class, seen = self._plan_rejections_exhausted(
            issue.id, result.validation_errors
        )
        repeat_line = ""
        if seen > 1:
            repeat_line = (
                f"**`{worst_class}` has now refused this issue {seen} times.** "
                f"Each is a separate HITL cycle, not a retry — the planner "
                f"already retried once with these errors in its prompt. "
                f"Re-labelling `hydraflow-ready` without changing the issue "
                f"asks the same planner for the same shape again.\n\n"
            )
        if exhausted:
            repeat_line += (
                f"That is at or past the "
                f"`plan_validation_decompose_threshold` "
                f"({self._config.plan_validation_decompose_threshold}) for one "
                f"gate, so this issue wants **decomposition** (ADR-0105) "
                f"rather than another planning attempt: the gate is refusing "
                f"an honest plan for work that does not fit one unit.\n\n"
            )
        hitl_comment = (
            f"## Plan Validation Failed\n\n"
            f"The planner was unable to produce a valid plan "
            f"after planning attempts for issue #{issue.id}.\n\n"
            f"{score_line}"
            f"{repeat_line}"
            f"**Validation errors:**\n{error_list}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(issue.id, hitl_comment)
        # Clear any accumulated adversarial state before HITL hand-off. Next
        # retry (after operator re-labels to hydraflow-ready) starts with a
        # fresh AdversarialState — otherwise the surfacer's concerns would
        # be appended on top of the prior attempt's, growing unboundedly
        # across HITL cycles.
        self._state.clear_adversarial_state(issue.id)
        if exhausted and await self._route_to_decomposition(issue, worst_class):
            return
        await self._escalator(
            issue,
            cause="Plan validation failed after retry",
            details="; ".join(result.validation_errors),
            category=FailureCategory.PLAN_VALIDATION,
        )
        logger.warning(
            "Planning failed validation for issue #%d after retry — escalated to HITL",
            issue.id,
        )

    async def _post_plan_transcript(
        self, issue: Task, result: PlanResult, *, status: str
    ) -> None:
        """File memory suggestion and post transcript summary."""
        if result.transcript:
            await self._suggest_memory(
                result.transcript, "planner", f"issue #{issue.id}"
            )
        if self._summarizer is not None and result.transcript:
            try:
                await self._summarizer.summarize_and_comment(
                    transcript=result.transcript,
                    issue_number=issue.id,
                    phase="plan",
                    status=status,
                    issue_title=issue.title,
                    duration_seconds=result.duration_seconds,
                    log_file=self._plan_log_reference(issue.id),
                    issue_labels=issue.tags,
                )
            except (RuntimeError, OSError) as exc:
                # CreditExhaustedError/AuthenticationError subclass RuntimeError,
                # so this clause would otherwise bury the one failure the loop
                # must pause on (#6855 class, #11666 audit sweep).
                reraise_on_credit_or_bug(exc)
                logger.exception(
                    "Failed to post transcript summary for issue #%d", issue.id
                )

    def _plan_log_reference(self, issue_number: int) -> str:
        """Return a display-friendly log path for planner transcripts."""
        log_path = self._config.log_dir / f"plan-issue-{issue_number}.txt"
        return self._config.format_path_for_display(log_path)
